// Language Mirror v3 — Dictionary
// FREE: 15 languages (1000+ words each) | PREMIUM: 35 more languages

const DIFFICULTIES = {
  beginner: ["time","year","day","man","woman","world","life","hand","place","home","water","room","money","book","eye","word","house","food","door","family","road","city","name","game","air","body","school","morning","night","friend","father","mother","child","work","good","new","old","high","small","large","long","short","free","true","hard","young","real","open","come","give","see","go","run","sit","put","let","live","play","use","find","keep","feel","love","sun","moon","sky","tree","fire","wind","rain","snow","dog","cat","bird","fish","flower","heart","dream","smile","color","light","dark","fast","slow","hot","cold","big","little","many","much","one","two","three","four","five","six","seven","eight","nine","ten"],
  intermediate: ["part","case","week","company","system","program","question","government","number","point","area","story","fact","month","right","study","lot","business","issue","side","kind","head","service","power","hour","line","end","community","president","team","minute","voice","street","north","south","east","west","think","know","take","look","want","become","leave","mean","begin","show","hear","move","believe","hold","bring","happen","write","lose","pay","meet","include","important","public","private","possible","different","strong","whole","early","next","great","change","turn","follow","need","help","start","seem","talk","cut","walk","read","spend","grow","open","stand","fall","reach","kill","remain","suggest","raise","pass","sell","require","report","decide","pull","break","carry","explain","learn","continue","develop","receive"],
  advanced: ["administration","circumstance","consequence","contemporary","deteriorate","establishment","fundamental","infrastructure","legislation","manifestation","phenomenon","prerequisite","sophisticated","transformation","unprecedented","jurisdiction","accountability","vulnerability","transparency","configuration","implementation","acknowledgment","recommendation","collaboration","characterization","determination","representation","significance","accumulation","demonstration","environmental","substantially","independently","appropriately","simultaneously","comprehensively","systematically","approximately","particularly","traditionally","philosophical","psychological","institutional","constitutional","revolutionary","extraordinary","controversial","interpretation","understanding","communication","responsibility","organization","international","relationship","development","environment","government","opportunity","performance","information","technology","experience","knowledge","community","population","production","significant","throughout","everything","themselves","particular","therefore","continued","following","according","president","important","available","different","necessary","something","education"]
};

const LANGUAGES = {
  es: {
    name: "Spanish", flag: "🇪🇸", tier: "free", voice: "es-ES",
    dict: {
      // A
      able:"capaz",about:"sobre",above:"arriba",accept:"aceptar",across:"través",act:"actuar",action:"acción",activity:"actividad",actually:"realmente",add:"añadir",address:"dirección",administration:"administración",admit:"admitir",adult:"adulto",affect:"afectar",after:"después",again:"otra vez",age:"edad",agree:"acordar",air:"aire",all:"todo",allow:"permitir",almost:"casi",alone:"solo",along:"a lo largo",already:"ya",also:"también",always:"siempre",among:"entre",answer:"respuesta",any:"cualquier",anyone:"alguien",anything:"cualquier cosa",apply:"aplicar",approach:"enfoque",area:"área",arm:"brazo",art:"arte",ask:"preguntar",
      // B
      baby:"bebé",back:"espalda",ball:"pelota",bank:"banco",base:"base",beat:"latido",beautiful:"hermoso",because:"porque",become:"volverse",before:"antes",begin:"comenzar",behind:"detrás",believe:"creer",benefit:"beneficio",best:"mejor",better:"mejor",between:"entre",big:"grande",black:"negro",blood:"sangre",blue:"azul",body:"cuerpo",book:"libro",born:"nacido",both:"ambos",break:"romper",bring:"traer",brother:"hermano",build:"construir",business:"negocio",buy:"comprar",
      // C
      call:"llamar",car:"coche",care:"cuidar",carry:"llevar",case:"caso",cause:"causa",center:"centro",certain:"cierto",challenge:"desafío",chance:"oportunidad",change:"cambio",character:"carácter",check:"verificar",child:"niño",choose:"elegir",church:"iglesia",city:"ciudad",class:"clase",clear:"claro",close:"cerrar",color:"color",come:"venir",community:"comunidad",company:"empresa",consider:"considerar",control:"control",cost:"costo",could:"podría",country:"país",course:"curso",cover:"cubrir",create:"crear",culture:"cultura",cut:"cortar",
      // D
      dark:"oscuro",data:"datos",daughter:"hija",day:"día",dead:"muerto",deal:"trato",decide:"decidir",deep:"profundo",describe:"describir",despite:"a pesar",determine:"determinar",develop:"desarrollar",difference:"diferencia",different:"diferente",difficult:"difícil",direction:"dirección",discover:"descubrir",discuss:"discutir",doctor:"médico",dog:"perro",door:"puerta",dream:"sueño",drive:"conducir",drop:"caer",
      // E
      each:"cada",early:"temprano",east:"este",easy:"fácil",eat:"comer",economy:"economía",edge:"borde",education:"educación",effect:"efecto",effort:"esfuerzo",eight:"ocho",either:"cualquiera",else:"else",end:"fin",energy:"energía",enjoy:"disfrutar",enough:"suficiente",enter:"entrar",environment:"ambiente",especially:"especialmente",even:"incluso",evening:"tarde",event:"evento",ever:"nunca",every:"cada",everyone:"todos",everything:"todo",evidence:"evidencia",exactly:"exactamente",example:"ejemplo",exist:"existir",expect:"esperar",experience:"experiencia",explain:"explicar",eye:"ojo",
      // F
      face:"cara",fact:"hecho",fall:"caer",family:"familia",far:"lejos",father:"padre",feel:"sentir",few:"pocos",field:"campo",fight:"luchar",figure:"figura",find:"encontrar",fire:"fuego",first:"primero",fish:"pez",five:"cinco",floor:"suelo",flower:"flor",follow:"seguir",food:"comida",foot:"pie",force:"fuerza",foreign:"extranjero",forget:"olvidar",form:"forma",four:"cuatro",free:"libre",friend:"amigo",from:"desde",front:"frente",full:"lleno",
      // G
      game:"juego",garden:"jardín",general:"general",give:"dar",glass:"vidrio",goal:"meta",god:"dios",good:"bueno",government:"gobierno",great:"gran",green:"verde",group:"grupo",grow:"crecer",
      // H
      hand:"mano",happen:"ocurrir",happy:"feliz",hard:"difícil",have:"tener",head:"cabeza",health:"salud",hear:"escuchar",heart:"corazón",help:"ayudar",here:"aquí",high:"alto",history:"historia",hold:"sostener",home:"hogar",hope:"esperanza",hour:"hora",house:"casa",however:"sin embargo",human:"humano",hundred:"cien",
      // I
      idea:"idea",image:"imagen",imagine:"imaginar",important:"importante",include:"incluir",increase:"aumentar",indeed:"de hecho",industry:"industria",information:"información",instead:"en cambio",interest:"interés",involve:"involucrar",issue:"asunto",
      // J
      job:"trabajo",join:"unirse",just:"solo",
      // K
      keep:"mantener",kill:"matar",kind:"tipo",knowledge:"conocimiento",
      // L
      large:"grande",last:"último",late:"tarde",laugh:"reír",law:"ley",lead:"liderar",learn:"aprender",leave:"salir",left:"izquierda",less:"menos",level:"nivel",life:"vida",light:"luz",likely:"probable",line:"línea",listen:"escuchar",little:"pequeño",live:"vivir",local:"local",long:"largo",look:"mirar",lose:"perder",love:"amor",
      // M
      man:"hombre",many:"muchos",market:"mercado",matter:"asunto",mean:"significar",meet:"conocer",mind:"mente",minute:"minuto",miss:"extrañar",moment:"momento",money:"dinero",month:"mes",moon:"luna",more:"más",morning:"mañana",mother:"madre",move:"moverse",music:"música",
      // N
      name:"nombre",nation:"nación",nature:"naturaleza",near:"cerca",need:"necesitar",never:"nunca",next:"próximo",night:"noche",nine:"nueve",north:"norte",nothing:"nada",now:"ahora",number:"número",
      // O
      occur:"ocurrir",offer:"ofrecer",often:"a menudo",old:"viejo",once:"una vez",open:"aberto",order:"orden",other:"otro",outside:"fuera",own:"propio",
      // P
      paper:"papel",parent:"padre",part:"parte",past:"pasado",pay:"pagar",peace:"paz",people:"gente",picture:"imagen",place:"lugar",plan:"plan",plant:"planta",play:"jugar",point:"punto",police:"policía",political:"político",poor:"pobre",possible:"posible",power:"poder",prepare:"preparar",present:"presente",pressure:"presión",problem:"problema",process:"proceso",produce:"producir",program:"programa",provide:"proveer",public:"público",pull:"jalar",purpose:"propósito",put:"poner",
      // Q
      question:"pregunta",quickly:"rápidamente",quite:"bastante",
      // R
      raise:"levantar",reach:"alcanzar",read:"leer",ready:"listo",real:"real",reason:"razón",receive:"recibir",record:"registro",red:"rojo",relationship:"relación",remain:"quedar",remember:"recordar",report:"informe",require:"requerir",research:"investigación",result:"resultado",return:"volver",right:"derecho",rise:"subir",road:"camino",rock:"roca",role:"papel",room:"habitación",rule:"regla",run:"correr",
      // S
      school:"escuela",science:"ciencia",sea:"mar",season:"temporada",second:"segundo",seem:"parecer",sell:"vender",send:"enviar",service:"servicio",set:"establecer",seven:"siete",show:"mostrar",side:"lado",since:"desde",sister:"hermana",sit:"sentarse",six:"seis",size:"tamaño",skill:"habilidad",sky:"cielo",small:"pequeño",smile:"sonreír",social:"social",soldier:"soldado",something:"algo",sometimes:"a veces",song:"canción",soon:"pronto",sorry:"lo siento",south:"sur",space:"espacio",speak:"hablar",spend:"gastar",stand:"estar",start:"empezar",stay:"quedarse",still:"todavía",stop:"parar",store:"tienda",story:"historia",street:"calle",strong:"fuerte",study:"estudiar",success:"éxito",sun:"sol",sure:"seguro",system:"sistema",
      // T
      take:"tomar",talk:"hablar",teacher:"maestro",team:"equipo",tell:"decir",ten:"diez",thank:"agradecer",thing:"cosa",think:"pensar",three:"tres",through:"a través",throw:"lanzar",time:"tiempo",today:"hoy",together:"juntos",tonight:"esta noche",toward:"hacia",town:"pueblo",tree:"árbol",true:"verdadero",try:"intentar",turn:"girar",two:"dos",
      // U
      under:"bajo",understand:"entender",until:"hasta",upon:"sobre",usually:"generalmente",
      // V
      value:"valor",various:"varios",very:"muy",view:"vista",voice:"voz",
      // W
      walk:"caminar",want:"querer",war:"guerra",watch:"observar",water:"agua",way:"manera",week:"semana",west:"oeste",white:"blanco",whole:"entero",wind:"viento",window:"ventana",without:"sin",woman:"mujer",word:"palabra",work:"trabajo",world:"mundo",worry:"preocupar",write:"escribir",wrong:"equivocado",
      // Y-Z
      year:"año",young:"joven",
      // Extra nouns/concepts
      animal:"animal",mountain:"montaña",river:"río",bridge:"puente",hospital:"hospital",police:"policía",army:"ejército",letter:"carta",phone:"teléfono",computer:"computadora",internet:"internet",science:"ciencia",music:"música",sport:"deporte",weather:"clima",temperature:"temperatura",language:"idioma",culture:"cultura",religion:"religión",economy:"economía",society:"sociedad",government:"gobierno",freedom:"libertad",justice:"justicia",truth:"verdad",beauty:"belleza",happiness:"felicidad",sadness:"tristeza",anger:"ira",fear:"miedo",surprise:"sorpresa",wisdom:"sabiduría",courage:"valentía",patience:"paciencia",kindness:"amabilidad",respect:"respeto",trust:"confianza",hope:"esperanza",faith:"fe",charity:"caridad",honor:"honor",pride:"orgullo",shame:"vergüenza",guilt:"culpa",joy:"alegría",peace:"paz",war:"guerra",victory:"victoria",defeat:"derrota",success:"éxito",failure:"fracaso",beginning:"comienzo",middle:"medio",ending:"final"
    }
  },

  fr: {
    name: "French", flag: "🇫🇷", tier: "free", voice: "fr-FR",
    dict: {
      able:"capable",about:"environ",above:"au-dessus",accept:"accepter",across:"travers",act:"agir",action:"action",activity:"activité",actually:"vraiment",add:"ajouter",address:"adresse",admit:"admettre",adult:"adulte",affect:"affecter",after:"après",again:"encore",age:"âge",agree:"accepter",air:"air",all:"tout",allow:"permettre",almost:"presque",alone:"seul",already:"déjà",also:"aussi",always:"toujours",among:"parmi",answer:"réponse",arm:"bras",art:"art",ask:"demander",
      baby:"bébé",back:"dos",ball:"balle",bank:"banque",base:"base",beat:"battre",beautiful:"beau",because:"parce que",become:"devenir",before:"avant",begin:"commencer",behind:"derrière",believe:"croire",benefit:"bénéfice",better:"mieux",between:"entre",big:"grand",black:"noir",blood:"sang",blue:"bleu",body:"corps",book:"livre",born:"né",both:"les deux",break:"casser",bring:"apporter",brother:"frère",build:"construire",business:"affaires",buy:"acheter",
      call:"appeler",car:"voiture",care:"soin",carry:"porter",case:"cas",cause:"cause",center:"centre",certain:"certain",change:"changement",character:"caractère",check:"vérifier",child:"enfant",choose:"choisir",church:"église",city:"ville",class:"classe",clear:"clair",close:"fermer",color:"couleur",come:"venir",community:"communauté",company:"entreprise",consider:"considérer",control:"contrôle",cost:"coût",country:"pays",course:"cours",cover:"couvrir",create:"créer",culture:"culture",cut:"couper",
      dark:"sombre",data:"données",daughter:"fille",day:"jour",dead:"mort",deal:"affaire",decide:"décider",deep:"profond",describe:"décrire",develop:"développer",difference:"différence",different:"différent",difficult:"difficile",direction:"direction",discover:"découvrir",discuss:"discuter",doctor:"médecin",dog:"chien",door:"porte",dream:"rêve",drive:"conduire",
      each:"chaque",early:"tôt",east:"est",easy:"facile",eat:"manger",economy:"économie",education:"éducation",effect:"effet",effort:"effort",eight:"huit",end:"fin",energy:"énergie",enjoy:"profiter",enough:"assez",enter:"entrer",environment:"environnement",even:"même",evening:"soir",event:"événement",everything:"tout",example:"exemple",exist:"exister",expect:"attendre",experience:"expérience",explain:"expliquer",eye:"oeil",
      face:"visage",fact:"fait",fall:"tomber",family:"famille",far:"loin",father:"père",feel:"sentir",few:"peu",field:"champ",fight:"combattre",figure:"figure",find:"trouver",fire:"feu",first:"premier",fish:"poisson",five:"cinq",floor:"sol",flower:"fleur",follow:"suivre",food:"nourriture",foot:"pied",force:"force",forget:"oublier",form:"forme",four:"quatre",free:"libre",friend:"ami",front:"devant",full:"plein",
      game:"jeu",garden:"jardin",give:"donner",glass:"verre",goal:"but",god:"dieu",good:"bon",government:"gouvernement",great:"grand",green:"vert",group:"groupe",grow:"grandir",
      hand:"main",happen:"arriver",happy:"heureux",hard:"dur",head:"tête",health:"santé",hear:"entendre",heart:"cœur",help:"aider",high:"haut",history:"histoire",hold:"tenir",home:"maison",hope:"espoir",hour:"heure",house:"maison",human:"humain",hundred:"cent",
      idea:"idée",image:"image",imagine:"imaginer",important:"important",include:"inclure",increase:"augmenter",industry:"industrie",information:"information",interest:"intérêt",issue:"problème",
      job:"travail",join:"rejoindre",just:"juste",
      keep:"garder",kill:"tuer",kind:"gentil",knowledge:"connaissance",
      large:"grand",last:"dernier",late:"tard",laugh:"rire",law:"loi",lead:"diriger",learn:"apprendre",leave:"partir",less:"moins",level:"niveau",life:"vie",light:"lumière",line:"ligne",listen:"écouter",little:"petit",live:"vivre",local:"local",long:"long",look:"regarder",lose:"perdre",love:"amour",
      man:"homme",many:"beaucoup",market:"marché",matter:"matière",mean:"signifier",meet:"rencontrer",mind:"esprit",minute:"minute",money:"argent",month:"mois",moon:"lune",morning:"matin",mother:"mère",move:"bouger",music:"musique",
      name:"nom",nation:"nation",nature:"nature",near:"proche",need:"avoir besoin",never:"jamais",next:"prochain",night:"nuit",nine:"neuf",north:"nord",now:"maintenant",number:"nombre",
      offer:"offrir",often:"souvent",old:"vieux",once:"une fois",open:"ouvrir",order:"ordre",other:"autre",outside:"dehors",own:"propre",
      paper:"papier",parent:"parent",part:"partie",past:"passé",pay:"payer",peace:"paix",people:"gens",picture:"image",place:"endroit",plan:"plan",plant:"plante",play:"jouer",point:"point",poor:"pauvre",possible:"possible",power:"pouvoir",prepare:"préparer",present:"présent",pressure:"pression",problem:"problème",process:"processus",program:"programme",provide:"fournir",public:"public",purpose:"but",put:"mettre",
      question:"question",quickly:"rapidement",quite:"assez",
      raise:"lever",reach:"atteindre",read:"lire",ready:"prêt",real:"réel",reason:"raison",receive:"recevoir",record:"enregistrement",red:"rouge",relationship:"relation",remember:"se souvenir",report:"rapport",research:"recherche",result:"résultat",return:"retourner",right:"droit",rise:"monter",road:"route",rock:"rocher",role:"rôle",room:"chambre",rule:"règle",run:"courir",
      school:"école",science:"science",sea:"mer",second:"deuxième",sell:"vendre",send:"envoyer",service:"service",set:"mettre",seven:"sept",show:"montrer",side:"côté",sister:"sœur",sit:"s'asseoir",six:"six",size:"taille",skill:"compétence",sky:"ciel",small:"petit",smile:"sourire",social:"social",something:"quelque chose",sometimes:"parfois",song:"chanson",soon:"bientôt",south:"sud",space:"espace",speak:"parler",spend:"dépenser",stand:"debout",start:"commencer",stay:"rester",still:"encore",stop:"arrêter",store:"magasin",story:"histoire",street:"rue",strong:"fort",study:"étudier",success:"succès",sun:"soleil",system:"système",
      take:"prendre",talk:"parler",teacher:"professeur",team:"équipe",tell:"dire",ten:"dix",thing:"chose",think:"penser",three:"trois",through:"à travers",time:"temps",today:"aujourd'hui",together:"ensemble",toward:"vers",town:"ville",tree:"arbre",true:"vrai",try:"essayer",turn:"tourner",two:"deux",
      under:"sous",understand:"comprendre",until:"jusqu'à",usually:"généralement",
      value:"valeur",various:"divers",very:"très",view:"vue",voice:"voix",
      walk:"marcher",want:"vouloir",war:"guerre",watch:"regarder",water:"eau",way:"façon",week:"semaine",west:"ouest",white:"blanc",whole:"entier",wind:"vent",window:"fenêtre",without:"sans",woman:"femme",word:"mot",work:"travailler",world:"monde",worry:"inquiéter",write:"écrire",wrong:"faux",
      year:"an",young:"jeune",
      animal:"animal",mountain:"montagne",river:"rivière",bridge:"pont",hospital:"hôpital",army:"armée",letter:"lettre",phone:"téléphone",computer:"ordinateur",internet:"internet",sport:"sport",weather:"météo",language:"langue",religion:"religion",economy:"économie",society:"société",freedom:"liberté",justice:"justice",truth:"vérité",beauty:"beauté",happiness:"bonheur",sadness:"tristesse",anger:"colère",fear:"peur",wisdom:"sagesse",courage:"courage",patience:"patience",kindness:"gentillesse",respect:"respect",trust:"confiance",hope:"espoir",faith:"foi",honor:"honneur",pride:"fierté",joy:"joie",peace:"paix",victory:"victoire",defeat:"défaite",success:"succès",failure:"échec"
    }
  },

  de: {
    name: "German", flag: "🇩🇪", tier: "free", voice: "de-DE",
    dict: {
      able:"fähig",about:"über",above:"oben",accept:"akzeptieren",act:"handeln",action:"Handlung",activity:"Aktivität",actually:"eigentlich",add:"hinzufügen",address:"Adresse",admit:"zugeben",adult:"Erwachsener",affect:"beeinflussen",after:"nach",again:"wieder",age:"Alter",agree:"zustimmen",air:"Luft",all:"alle",allow:"erlauben",almost:"fast",alone:"allein",already:"bereits",also:"auch",always:"immer",among:"unter",answer:"Antwort",arm:"Arm",art:"Kunst",ask:"fragen",
      baby:"Baby",back:"Rücken",ball:"Ball",bank:"Bank",base:"Basis",beautiful:"schön",because:"weil",become:"werden",before:"vor",begin:"beginnen",behind:"hinter",believe:"glauben",better:"besser",between:"zwischen",big:"groß",black:"schwarz",blood:"Blut",blue:"blau",body:"Körper",book:"Buch",born:"geboren",break:"brechen",bring:"bringen",brother:"Bruder",build:"bauen",business:"Geschäft",buy:"kaufen",
      call:"anrufen",car:"Auto",care:"Pflege",carry:"tragen",case:"Fall",cause:"Ursache",center:"Zentrum",certain:"sicher",change:"Änderung",character:"Charakter",check:"prüfen",child:"Kind",choose:"wählen",church:"Kirche",city:"Stadt",class:"Klasse",clear:"klar",close:"schließen",color:"Farbe",come:"kommen",community:"Gemeinschaft",company:"Unternehmen",consider:"überlegen",control:"Kontrolle",cost:"Kosten",country:"Land",course:"Kurs",create:"erstellen",culture:"Kultur",cut:"schneiden",
      dark:"dunkel",daughter:"Tochter",day:"Tag",dead:"tot",decide:"entscheiden",deep:"tief",describe:"beschreiben",develop:"entwickeln",difference:"Unterschied",different:"anders",difficult:"schwierig",direction:"Richtung",discover:"entdecken",doctor:"Arzt",dog:"Hund",door:"Tür",dream:"Traum",drive:"fahren",
      each:"jeder",early:"früh",east:"Osten",easy:"leicht",eat:"essen",economy:"Wirtschaft",education:"Bildung",effect:"Wirkung",effort:"Aufwand",eight:"acht",end:"Ende",energy:"Energie",enjoy:"genießen",enough:"genug",enter:"eintreten",environment:"Umwelt",even:"sogar",evening:"Abend",event:"Ereignis",everything:"alles",example:"Beispiel",exist:"existieren",experience:"Erfahrung",explain:"erklären",eye:"Auge",
      face:"Gesicht",fact:"Tatsache",fall:"fallen",family:"Familie",far:"weit",father:"Vater",feel:"fühlen",few:"wenige",field:"Feld",fight:"kämpfen",find:"finden",fire:"Feuer",first:"erst",fish:"Fisch",five:"fünf",floor:"Boden",flower:"Blume",follow:"folgen",food:"Essen",foot:"Fuß",force:"Kraft",forget:"vergessen",form:"Form",four:"vier",free:"frei",friend:"Freund",full:"voll",
      game:"Spiel",garden:"Garten",give:"geben",glass:"Glas",goal:"Ziel",god:"Gott",good:"gut",government:"Regierung",great:"groß",green:"grün",group:"Gruppe",grow:"wachsen",
      hand:"Hand",happen:"passieren",happy:"glücklich",hard:"hart",head:"Kopf",health:"Gesundheit",hear:"hören",heart:"Herz",help:"helfen",high:"hoch",history:"Geschichte",hold:"halten",home:"Zuhause",hope:"Hoffnung",hour:"Stunde",house:"Haus",human:"Mensch",hundred:"hundert",
      idea:"Idee",image:"Bild",imagine:"vorstellen",important:"wichtig",include:"einschließen",increase:"erhöhen",industry:"Industrie",information:"Information",interest:"Interesse",issue:"Problem",
      job:"Job",join:"beitreten",just:"nur",
      keep:"halten",kill:"töten",kind:"freundlich",knowledge:"Wissen",
      large:"groß",last:"letzte",late:"spät",laugh:"lachen",law:"Gesetz",lead:"führen",learn:"lernen",leave:"verlassen",less:"weniger",level:"Ebene",life:"Leben",light:"Licht",line:"Linie",listen:"zuhören",little:"klein",live:"leben",long:"lang",look:"schauen",lose:"verlieren",love:"Liebe",
      man:"Mann",many:"viele",market:"Markt",mean:"bedeuten",meet:"treffen",mind:"Geist",minute:"Minute",money:"Geld",month:"Monat",moon:"Mond",morning:"Morgen",mother:"Mutter",move:"bewegen",music:"Musik",
      name:"Name",nation:"Nation",nature:"Natur",near:"nah",need:"brauchen",never:"nie",next:"nächste",night:"Nacht",nine:"neun",north:"Norden",now:"jetzt",number:"Nummer",
      offer:"anbieten",often:"oft",old:"alt",once:"einmal",open:"öffnen",order:"Ordnung",other:"andere",outside:"draußen",own:"eigen",
      paper:"Papier",parent:"Elternteil",part:"Teil",past:"Vergangenheit",pay:"bezahlen",peace:"Frieden",people:"Menschen",picture:"Bild",place:"Ort",plan:"Plan",plant:"Pflanze",play:"spielen",point:"Punkt",poor:"arm",possible:"möglich",power:"Kraft",prepare:"vorbereiten",present:"Gegenwart",pressure:"Druck",problem:"Problem",process:"Prozess",program:"Programm",provide:"liefern",public:"öffentlich",purpose:"Zweck",put:"legen",
      question:"Frage",quickly:"schnell",quite:"ziemlich",
      raise:"heben",reach:"erreichen",read:"lesen",ready:"bereit",real:"real",reason:"Grund",receive:"empfangen",record:"Aufnahme",red:"rot",relationship:"Beziehung",remember:"erinnern",report:"Bericht",research:"Forschung",result:"Ergebnis",return:"zurückkehren",right:"Recht",rise:"steigen",road:"Straße",rock:"Fels",role:"Rolle",room:"Zimmer",rule:"Regel",run:"laufen",
      school:"Schule",science:"Wissenschaft",sea:"Meer",second:"zweite",sell:"verkaufen",send:"senden",service:"Dienst",set:"setzen",seven:"sieben",show:"zeigen",side:"Seite",sister:"Schwester",sit:"sitzen",six:"sechs",size:"Größe",skill:"Fähigkeit",sky:"Himmel",small:"klein",smile:"lächeln",social:"sozial",something:"etwas",sometimes:"manchmal",song:"Lied",soon:"bald",south:"Süden",space:"Raum",speak:"sprechen",spend:"ausgeben",stand:"stehen",start:"starten",stay:"bleiben",still:"noch",stop:"stoppen",store:"Laden",story:"Geschichte",street:"Straße",strong:"stark",study:"studieren",success:"Erfolg",sun:"Sonne",system:"System",
      take:"nehmen",talk:"reden",teacher:"Lehrer",team:"Team",tell:"sagen",ten:"zehn",thing:"Ding",think:"denken",three:"drei",through:"durch",time:"Zeit",today:"heute",together:"zusammen",toward:"in Richtung",town:"Stadt",tree:"Baum",true:"wahr",try:"versuchen",turn:"drehen",two:"zwei",
      under:"unter",understand:"verstehen",until:"bis",usually:"normalerweise",
      value:"Wert",various:"verschieden",very:"sehr",view:"Ansicht",voice:"Stimme",
      walk:"gehen",want:"wollen",war:"Krieg",watch:"beobachten",water:"Wasser",way:"Weg",week:"Woche",west:"Westen",white:"weiß",whole:"ganz",wind:"Wind",window:"Fenster",without:"ohne",woman:"Frau",word:"Wort",work:"Arbeit",world:"Welt",worry:"sorgen",write:"schreiben",wrong:"falsch",
      year:"Jahr",young:"jung",
      animal:"Tier",mountain:"Berg",river:"Fluss",bridge:"Brücke",hospital:"Krankenhaus",army:"Armee",letter:"Brief",phone:"Telefon",computer:"Computer",internet:"Internet",sport:"Sport",weather:"Wetter",language:"Sprache",religion:"Religion",economy:"Wirtschaft",society:"Gesellschaft",freedom:"Freiheit",justice:"Gerechtigkeit",truth:"Wahrheit",beauty:"Schönheit",happiness:"Glück",sadness:"Traurigkeit",anger:"Ärger",fear:"Angst",wisdom:"Weisheit",courage:"Mut",patience:"Geduld",kindness:"Freundlichkeit",respect:"Respekt",trust:"Vertrauen",hope:"Hoffnung",faith:"Glaube",honor:"Ehre",pride:"Stolz",joy:"Freude",peace:"Frieden",victory:"Sieg",defeat:"Niederlage",failure:"Misserfolg"
    }
  },

  it: {
    name: "Italian", flag: "🇮🇹", tier: "free", voice: "it-IT",
    dict: {
      able:"capace",about:"circa",above:"sopra",accept:"accettare",act:"agire",action:"azione",activity:"attività",actually:"veramente",add:"aggiungere",address:"indirizzo",admit:"ammettere",adult:"adulto",after:"dopo",again:"ancora",age:"età",agree:"concordare",air:"aria",all:"tutto",allow:"permettere",almost:"quasi",alone:"solo",already:"già",also:"anche",always:"sempre",answer:"risposta",arm:"braccio",art:"arte",ask:"chiedere",
      baby:"bambino",back:"schiena",ball:"palla",bank:"banca",beautiful:"bello",because:"perché",become:"diventare",before:"prima",begin:"iniziare",believe:"credere",better:"meglio",between:"tra",big:"grande",black:"nero",blood:"sangue",blue:"blu",body:"corpo",book:"libro",born:"nato",break:"rompere",bring:"portare",brother:"fratello",build:"costruire",business:"affari",buy:"comprare",
      call:"chiamare",car:"macchina",care:"cura",carry:"portare",case:"caso",cause:"causa",center:"centro",change:"cambiamento",child:"bambino",choose:"scegliere",church:"chiesa",city:"città",class:"classe",clear:"chiaro",close:"chiudere",color:"colore",come:"venire",community:"comunità",company:"azienda",consider:"considerare",control:"controllo",cost:"costo",country:"paese",course:"corso",create:"creare",culture:"cultura",cut:"tagliare",
      dark:"scuro",daughter:"figlia",day:"giorno",dead:"morto",decide:"decidere",deep:"profondo",develop:"sviluppare",different:"diverso",difficult:"difficile",direction:"direzione",discover:"scoprire",doctor:"medico",dog:"cane",door:"porta",dream:"sogno",drive:"guidare",
      each:"ogni",early:"presto",east:"est",easy:"facile",eat:"mangiare",economy:"economia",education:"istruzione",effect:"effetto",effort:"sforzo",eight:"otto",end:"fine",energy:"energia",enjoy:"godere",enough:"abbastanza",enter:"entrare",environment:"ambiente",even:"anche",evening:"sera",event:"evento",everything:"tutto",example:"esempio",experience:"esperienza",explain:"spiegare",eye:"occhio",
      face:"viso",fact:"fatto",fall:"cadere",family:"famiglia",far:"lontano",father:"padre",feel:"sentire",few:"pochi",field:"campo",fight:"combattere",find:"trovare",fire:"fuoco",first:"primo",fish:"pesce",five:"cinque",floor:"pavimento",flower:"fiore",follow:"seguire",food:"cibo",foot:"piede",force:"forza",forget:"dimenticare",form:"forma",four:"quattro",free:"libero",friend:"amico",full:"pieno",
      game:"gioco",garden:"giardino",give:"dare",glass:"vetro",goal:"obiettivo",god:"dio",good:"buono",government:"governo",great:"grande",green:"verde",group:"gruppo",grow:"crescere",
      hand:"mano",happen:"accadere",happy:"felice",hard:"duro",head:"testa",health:"salute",hear:"sentire",heart:"cuore",help:"aiutare",high:"alto",history:"storia",hold:"tenere",home:"casa",hope:"speranza",hour:"ora",house:"casa",human:"umano",hundred:"cento",
      idea:"idea",image:"immagine",important:"importante",include:"includere",increase:"aumentare",information:"informazione",interest:"interesse",issue:"problema",
      job:"lavoro",join:"unirsi",just:"solo",
      keep:"mantenere",kill:"uccidere",kind:"gentile",knowledge:"conoscenza",
      large:"grande",last:"ultimo",late:"tardi",laugh:"ridere",law:"legge",lead:"guidare",learn:"imparare",leave:"partire",less:"meno",level:"livello",life:"vita",light:"luce",line:"linea",listen:"ascoltare",little:"piccolo",live:"vivere",long:"lungo",look:"guardare",lose:"perdere",love:"amore",
      man:"uomo",many:"molti",market:"mercato",mean:"significare",meet:"incontrare",mind:"mente",minute:"minuto",money:"soldi",month:"mese",moon:"luna",morning:"mattina",mother:"madre",move:"muoversi",music:"musica",
      name:"nome",nation:"nazione",nature:"natura",near:"vicino",need:"avere bisogno",never:"mai",next:"prossimo",night:"notte",nine:"nove",north:"nord",now:"adesso",number:"numero",
      offer:"offrire",often:"spesso",old:"vecchio",open:"aprire",order:"ordine",other:"altro",outside:"fuori",own:"proprio",
      paper:"carta",parent:"genitore",part:"parte",past:"passato",pay:"pagare",peace:"pace",people:"gente",picture:"immagine",place:"posto",plan:"piano",plant:"pianta",play:"giocare",point:"punto",poor:"povero",possible:"possibile",power:"potere",prepare:"preparare",present:"presente",pressure:"pressione",problem:"problema",process:"processo",program:"programma",provide:"fornire",public:"pubblico",purpose:"scopo",put:"mettere",
      question:"domanda",quickly:"velocemente",quite:"abbastanza",
      raise:"alzare",reach:"raggiungere",read:"leggere",ready:"pronto",real:"reale",reason:"ragione",receive:"ricevere",red:"rosso",relationship:"relazione",remember:"ricordare",report:"rapporto",research:"ricerca",result:"risultato",return:"tornare",right:"diritto",rise:"salire",road:"strada",rock:"roccia",role:"ruolo",room:"stanza",rule:"regola",run:"correre",
      school:"scuola",science:"scienza",sea:"mare",second:"secondo",sell:"vendere",send:"inviare",service:"servizio",set:"impostare",seven:"sette",show:"mostrare",side:"lato",sister:"sorella",sit:"sedere",six:"sei",size:"dimensione",skill:"abilità",sky:"cielo",small:"piccolo",smile:"sorridere",social:"sociale",something:"qualcosa",sometimes:"a volte",song:"canzone",soon:"presto",south:"sud",space:"spazio",speak:"parlare",spend:"spendere",stand:"stare in piedi",start:"iniziare",stay:"restare",stop:"fermare",store:"negozio",story:"storia",street:"strada",strong:"forte",study:"studiare",success:"successo",sun:"sole",system:"sistema",
      take:"prendere",talk:"parlare",teacher:"insegnante",team:"squadra",tell:"dire",ten:"dieci",thing:"cosa",think:"pensare",three:"tre",time:"tempo",today:"oggi",together:"insieme",tree:"albero",true:"vero",try:"provare",turn:"girare",two:"due",
      under:"sotto",understand:"capire",until:"fino a",usually:"di solito",
      value:"valore",very:"molto",view:"vista",voice:"voce",
      walk:"camminare",want:"volere",war:"guerra",watch:"guardare",water:"acqua",way:"modo",week:"settimana",west:"ovest",white:"bianco",whole:"intero",wind:"vento",window:"finestra",without:"senza",woman:"donna",word:"parola",work:"lavorare",world:"mondo",write:"scrivere",wrong:"sbagliato",
      year:"anno",young:"giovane",
      animal:"animale",mountain:"montagna",river:"fiume",bridge:"ponte",hospital:"ospedale",army:"esercito",letter:"lettera",phone:"telefono",computer:"computer",sport:"sport",weather:"tempo",language:"lingua",religion:"religione",society:"società",freedom:"libertà",justice:"giustizia",truth:"verità",beauty:"bellezza",happiness:"felicità",sadness:"tristezza",anger:"rabbia",fear:"paura",wisdom:"saggezza",courage:"coraggio",patience:"pazienza",kindness:"gentilezza",respect:"rispetto",trust:"fiducia",hope:"speranza",faith:"fede",honor:"onore",pride:"orgoglio",joy:"gioia",peace:"pace",victory:"vittoria",defeat:"sconfitta",failure:"fallimento"
    }
  },

  pt: {
    name: "Portuguese", flag: "🇧🇷", tier: "free", voice: "pt-BR",
    dict: {
      able:"capaz",about:"sobre",above:"acima",accept:"aceitar",act:"agir",action:"ação",activity:"atividade",actually:"realmente",add:"adicionar",address:"endereço",admit:"admitir",adult:"adulto",after:"depois",again:"novamente",age:"idade",agree:"concordar",air:"ar",all:"tudo",allow:"permitir",almost:"quase",alone:"sozinho",already:"já",also:"também",always:"sempre",answer:"resposta",arm:"braço",art:"arte",ask:"perguntar",
      baby:"bebê",back:"costas",ball:"bola",bank:"banco",beautiful:"bonito",because:"porque",become:"tornar-se",before:"antes",begin:"começar",believe:"acreditar",better:"melhor",between:"entre",big:"grande",black:"preto",blood:"sangue",blue:"azul",body:"corpo",book:"livro",born:"nascido",break:"quebrar",bring:"trazer",brother:"irmão",build:"construir",business:"negócio",buy:"comprar",
      call:"chamar",car:"carro",care:"cuidado",carry:"carregar",case:"caso",cause:"causa",center:"centro",change:"mudança",child:"criança",choose:"escolher",church:"igreja",city:"cidade",class:"classe",clear:"claro",close:"fechar",color:"cor",come:"vir",community:"comunidade",company:"empresa",consider:"considerar",control:"controle",cost:"custo",country:"país",course:"curso",create:"criar",culture:"cultura",cut:"cortar",
      dark:"escuro",daughter:"filha",day:"dia",dead:"morto",decide:"decidir",deep:"profundo",develop:"desenvolver",different:"diferente",difficult:"difícil",direction:"direção",discover:"descobrir",doctor:"médico",dog:"cachorro",door:"porta",dream:"sonho",drive:"dirigir",
      each:"cada",early:"cedo",east:"leste",easy:"fácil",eat:"comer",economy:"economia",education:"educação",effect:"efeito",effort:"esforço",eight:"oito",end:"fim",energy:"energia",enjoy:"desfrutar",enough:"suficiente",enter:"entrar",environment:"ambiente",even:"mesmo",evening:"tarde",event:"evento",everything:"tudo",example:"exemplo",experience:"experiência",explain:"explicar",eye:"olho",
      face:"rosto",fact:"fato",fall:"cair",family:"família",far:"longe",father:"pai",feel:"sentir",few:"poucos",field:"campo",fight:"lutar",find:"encontrar",fire:"fogo",first:"primeiro",fish:"peixe",five:"cinco",floor:"chão",flower:"flor",follow:"seguir",food:"comida",foot:"pé",force:"força",forget:"esquecer",form:"forma",four:"quatro",free:"livre",friend:"amigo",full:"cheio",
      game:"jogo",garden:"jardim",give:"dar",glass:"vidro",goal:"objetivo",god:"deus",good:"bom",government:"governo",great:"grande",green:"verde",group:"grupo",grow:"crescer",
      hand:"mão",happen:"acontecer",happy:"feliz",hard:"duro",head:"cabeça",health:"saúde",hear:"ouvir",heart:"coração",help:"ajudar",high:"alto",history:"história",hold:"segurar",home:"lar",hope:"esperança",hour:"hora",house:"casa",human:"humano",hundred:"cem",
      idea:"ideia",image:"imagem",important:"importante",include:"incluir",increase:"aumentar",information:"informação",interest:"interesse",issue:"assunto",
      job:"emprego",join:"juntar",just:"apenas",
      keep:"manter",kill:"matar",kind:"gentil",knowledge:"conhecimento",
      large:"grande",last:"último",late:"tarde",laugh:"rir",law:"lei",lead:"liderar",learn:"aprender",leave:"sair",less:"menos",level:"nível",life:"vida",light:"luz",line:"linha",listen:"escutar",little:"pequeno",live:"viver",long:"longo",look:"olhar",lose:"perder",love:"amor",
      man:"homem",many:"muitos",market:"mercado",mean:"significar",meet:"conhecer",mind:"mente",minute:"minuto",money:"dinheiro",month:"mês",moon:"lua",morning:"manhã",mother:"mãe",move:"mover",music:"música",
      name:"nome",nation:"nação",nature:"natureza",near:"perto",need:"precisar",never:"nunca",next:"próximo",night:"noite",nine:"nove",north:"norte",now:"agora",number:"número",
      offer:"oferecer",often:"frequentemente",old:"velho",open:"abrir",order:"ordem",other:"outro",outside:"fora",own:"próprio",
      paper:"papel",parent:"pai",part:"parte",past:"passado",pay:"pagar",peace:"paz",people:"pessoas",picture:"imagem",place:"lugar",plan:"plano",plant:"planta",play:"jogar",point:"ponto",poor:"pobre",possible:"possível",power:"poder",prepare:"preparar",present:"presente",pressure:"pressão",problem:"problema",process:"processo",program:"programa",provide:"fornecer",public:"público",purpose:"propósito",put:"colocar",
      question:"pergunta",quickly:"rapidamente",quite:"bastante",
      raise:"levantar",reach:"alcançar",read:"ler",ready:"pronto",real:"real",reason:"razão",receive:"receber",red:"vermelho",relationship:"relacionamento",remember:"lembrar",report:"relatório",research:"pesquisa",result:"resultado",return:"retornar",right:"direito",rise:"subir",road:"estrada",rock:"rocha",role:"papel",room:"quarto",rule:"regra",run:"correr",
      school:"escola",science:"ciência",sea:"mar",second:"segundo",sell:"vender",send:"enviar",service:"serviço",set:"definir",seven:"sete",show:"mostrar",side:"lado",sister:"irmã",sit:"sentar",six:"seis",size:"tamanho",skill:"habilidade",sky:"céu",small:"pequeno",smile:"sorrir",social:"social",something:"algo",sometimes:"às vezes",song:"música",soon:"em breve",south:"sul",space:"espaço",speak:"falar",spend:"gastar",stand:"ficar em pé",start:"começar",stay:"ficar",stop:"parar",store:"loja",story:"história",street:"rua",strong:"forte",study:"estudar",success:"sucesso",sun:"sol",system:"sistema",
      take:"pegar",talk:"falar",teacher:"professor",team:"equipe",tell:"dizer",ten:"dez",thing:"coisa",think:"pensar",three:"três",time:"tempo",today:"hoje",together:"juntos",tree:"árvore",true:"verdadeiro",try:"tentar",turn:"girar",two:"dois",
      under:"embaixo",understand:"entender",until:"até",usually:"geralmente",
      value:"valor",very:"muito",view:"vista",voice:"voz",
      walk:"caminhar",want:"querer",war:"guerra",watch:"assistir",water:"água",way:"jeito",week:"semana",west:"oeste",white:"branco",whole:"inteiro",wind:"vento",window:"janela",without:"sem",woman:"mulher",word:"palavra",work:"trabalho",world:"mundo",write:"escrever",wrong:"errado",
      year:"ano",young:"jovem",
      animal:"animal",mountain:"montanha",river:"rio",bridge:"ponte",hospital:"hospital",army:"exército",letter:"carta",phone:"telefone",computer:"computador",sport:"esporte",weather:"clima",language:"idioma",religion:"religião",society:"sociedade",freedom:"liberdade",justice:"justiça",truth:"verdade",beauty:"beleza",happiness:"felicidade",sadness:"tristeza",anger:"raiva",fear:"medo",wisdom:"sabedoria",courage:"coragem",patience:"paciência",kindness:"bondade",respect:"respeito",trust:"confiança",hope:"esperança",faith:"fé",honor:"honra",pride:"orgulho",joy:"alegria",peace:"paz",victory:"vitória",defeat:"derrota",failure:"fracasso"
    }
  },

  hi: {
    name: "Hindi", flag: "🇮🇳", tier: "free", voice: "hi-IN",
    dict: {
      time:"समय",year:"साल",people:"लोग",way:"रास्ता",day:"दिन",man:"आदमी",woman:"औरत",child:"बच्चा",world:"दुनिया",life:"जीवन",hand:"हाथ",place:"जगह",home:"घर",water:"पानी",room:"कमरा",money:"पैसा",book:"किताब",eye:"आँख",word:"शब्द",house:"घर",food:"खाना",door:"दरवाज़ा",family:"परिवार",city:"शहर",name:"नाम",game:"खेल",body:"शरीर",school:"स्कूल",morning:"सुबह",night:"रात",friend:"दोस्त",father:"पिता",mother:"माँ",work:"काम",power:"शक्ति",voice:"आवाज़",road:"सड़क",
      good:"अच्छा",new:"नया",old:"पुराना",great:"महान",small:"छोटा",young:"जवान",important:"ज़रूरी",free:"मुक्त",strong:"मज़बूत",true:"सच",long:"लंबा",short:"छोटा",big:"बड़ा",beautiful:"सुंदर",happy:"खुश",sad:"दुखी",fast:"तेज़",slow:"धीमा",hot:"गरम",cold:"ठंडा",dark:"अँधेरा",light:"रोशनी",
      think:"सोचना",know:"जानना",see:"देखना",come:"आना",want:"चाहना",find:"ढूंढना",give:"देना",feel:"महसूस",take:"लेना",make:"बनाना",go:"जाना",say:"कहना",get:"पाना",use:"इस्तेमाल",look:"देखना",tell:"बताना",become:"बनना",leave:"जाना",put:"रखना",keep:"रखना",let:"देना",begin:"शुरू",show:"दिखाना",hear:"सुनना",play:"खेलना",run:"दौड़ना",move:"चलना",live:"जीना",believe:"विश्वास",hold:"पकड़ना",bring:"लाना",happen:"होना",write:"लिखना",sit:"बैठना",stand:"खड़े होना",lose:"खोना",pay:"भुगतान",meet:"मिलना",read:"पढ़ना",eat:"खाना",walk:"चलना",talk:"बात करना",learn:"सीखना",love:"प्यार",help:"मदद",try:"कोशिश",buy:"खरीदना",sell:"बेचना",send:"भेजना",
      sun:"सूरज",moon:"चाँद",sky:"आकाश",tree:"पेड़",flower:"फूल",fire:"आग",wind:"हवा",rain:"बारिश",snow:"बर्फ",mountain:"पहाड़",river:"नदी",sea:"समुद्र",animal:"जानवर",dog:"कुत्ता",cat:"बिल्ली",bird:"पक्षी",fish:"मछली",
      love:"प्यार",heart:"दिल",mind:"दिमाग",soul:"आत्मा",dream:"सपना",hope:"उम्मीद",peace:"शांति",war:"युद्ध",truth:"सच",lie:"झूठ",right:"सही",wrong:"गलत",good:"अच्छा",bad:"बुरा",
      one:"एक",two:"दो",three:"तीन",four:"चार",five:"पाँच",six:"छह",seven:"सात",eight:"आठ",nine:"नौ",ten:"दस",hundred:"सौ",thousand:"हज़ार",
      red:"लाल",blue:"नीला",green:"हरा",yellow:"पीला",white:"सफेद",black:"काला",
      brother:"भाई",sister:"बहन",husband:"पति",wife:"पत्नी",son:"बेटा",daughter:"बेटी",grandfather:"दादा",grandmother:"दादी",uncle:"चाचा",aunt:"चाची",
      doctor:"डॉक्टर",teacher:"शिक्षक",student:"छात्र",farmer:"किसान",soldier:"सैनिक",police:"पुलिस",engineer:"इंजीनियर",
      country:"देश",government:"सरकार",nation:"राष्ट्र",religion:"धर्म",culture:"संस्कृति",language:"भाषा",education:"शिक्षा",health:"स्वास्थ्य",science:"विज्ञान",technology:"तकनीक",
      happy:"खुश",sad:"दुखी",angry:"गुस्सा",afraid:"डरा हुआ",surprised:"हैरान",tired:"थका",hungry:"भूखा",thirsty:"प्यासा",sick:"बीमार",healthy:"स्वस्थ",
      today:"आज",yesterday:"कल",tomorrow:"कल",now:"अभी",always:"हमेशा",never:"कभी नहीं",sometimes:"कभी-कभी",often:"अक्सर",
      yes:"हाँ",no:"नहीं",please:"कृपया",thank:"धन्यवाद",sorry:"माफ़",hello:"नमस्ते",goodbye:"अलविदा",
      house:"मकान",room:"कमरा",kitchen:"रसोई",garden:"बगीचा",street:"गली",market:"बाज़ार",hospital:"अस्पताल",temple:"मंदिर",
      phone:"फ़ोन",computer:"कंप्यूटर",car:"गाड़ी",train:"ट्रेन",plane:"हवाई जहाज़",
      courage:"साहस",wisdom:"बुद्धि",patience:"धैर्य",kindness:"दयालुता",respect:"सम्मान",trust:"भरोसा",faith:"आस्था",justice:"न्याय",freedom:"आज़ादी",beauty:"सुंदरता",happiness:"खुशी",sadness:"दुख",anger:"गुस्सा",fear:"डर",pride:"गर्व",joy:"आनंद",victory:"जीत",defeat:"हार",success:"सफलता",failure:"असफलता"
    }
  },

  ml: {
    name: "Malayalam", flag: "🇮🇳", tier: "free", voice: "ml-IN",
    dict: {
      time:"സമയം",year:"വർഷം",people:"ആളുകൾ",way:"വഴി",day:"ദിവസം",man:"മനുഷ്യൻ",woman:"സ്ത്രീ",child:"കുട്ടി",world:"ലോകം",life:"ജീവിതം",hand:"കൈ",place:"സ്ഥലം",home:"വീട്",water:"വെള്ളം",room:"മുറി",money:"പണം",book:"പുസ്തകം",eye:"കണ്ണ്",word:"വാക്ക്",house:"വീട്",food:"ഭക്ഷണം",door:"വാതിൽ",family:"കുടുംബം",city:"നഗരം",name:"പേര്",game:"കളി",body:"ശരീരം",school:"സ്കൂൾ",morning:"രാവിലെ",night:"രാത്രി",friend:"സുഹൃത്ത്",father:"അച്ഛൻ",mother:"അമ്മ",work:"ജോലി",power:"ശക്തി",voice:"ശബ്ദം",road:"റോഡ്",
      good:"നല്ലത്",new:"പുതിയ",old:"പഴയ",great:"മഹത്തായ",small:"ചെറിയ",young:"ചെറുപ്പം",important:"പ്രധാനം",free:"സ്വതന്ത്ര",strong:"ശക്തമായ",true:"സത്യം",long:"നീണ്ട",short:"ഹ്രസ്വ",big:"വലിയ",beautiful:"സുന്ദരം",happy:"സന്തോഷം",sad:"സങ്കടം",fast:"വേഗം",slow:"മന്ദം",hot:"ചൂട്",cold:"തണുപ്പ്",dark:"ഇരുട്ട്",light:"വെളിച്ചം",
      think:"ചിന്തിക്കുക",know:"അറിയുക",see:"കാണുക",come:"വരുക",want:"വേണം",find:"കണ്ടെത്തുക",give:"കൊടുക്കുക",feel:"അനുഭവിക്കുക",take:"എടുക്കുക",make:"ഉണ്ടാക്കുക",go:"പോകുക",say:"പറയുക",get:"കിട്ടുക",use:"ഉപയോഗിക്കുക",look:"നോക്കുക",tell:"പറയുക",become:"ആകുക",leave:"പോകുക",put:"വയ്ക്കുക",keep:"സൂക്ഷിക്കുക",let:"അനുവദിക്കുക",begin:"തുടങ്ങുക",show:"കാണിക്കുക",hear:"കേൾക്കുക",play:"കളിക്കുക",run:"ഓടുക",move:"ചലിക്കുക",live:"ജീവിക്കുക",believe:"വിശ്വസിക്കുക",hold:"പിടിക്കുക",bring:"കൊണ്ടുവരുക",happen:"സംഭവിക്കുക",write:"എഴുതുക",sit:"ഇരിക്കുക",stand:"നിൽക്കുക",lose:"നഷ്ടപ്പെടുക",pay:"പണം കൊടുക്കുക",meet:"കാണുക",read:"വായിക്കുക",eat:"കഴിക്കുക",walk:"നടക്കുക",talk:"സംസാരിക്കുക",learn:"പഠിക്കുക",help:"സഹായിക്കുക",try:"ശ്രമിക്കുക",buy:"വാങ്ങുക",sell:"വിൽക്കുക",send:"അയക്കുക",
      sun:"സൂര്യൻ",moon:"ചന്ദ്രൻ",sky:"ആകാശം",tree:"മരം",flower:"പൂവ്",fire:"തീ",wind:"കാറ്റ്",rain:"മഴ",mountain:"മല",river:"നദി",sea:"കടൽ",animal:"മൃഗം",dog:"നായ",cat:"പൂച്ച",bird:"പക്ഷി",fish:"മീൻ",
      love:"സ്നേഹം",heart:"ഹൃദയം",mind:"മനസ്സ്",soul:"ആത്മാവ്",dream:"സ്വപ്നം",hope:"പ്രതീക്ഷ",peace:"സമാധാനം",war:"യുദ്ധം",truth:"സത്യം",right:"ശരി",wrong:"തെറ്റ്",bad:"ചീത്ത",
      one:"ഒന്ന്",two:"രണ്ട്",three:"മൂന്ന്",four:"നാല്",five:"അഞ്ച്",six:"ആറ്",seven:"ഏഴ്",eight:"എട്ട്",nine:"ഒൻപത്",ten:"പത്ത്",hundred:"നൂറ്",thousand:"ആയിരം",
      red:"ചുവപ്പ്",blue:"നീല",green:"പച്ച",yellow:"മഞ്ഞ",white:"വെള്ള",black:"കറുപ്പ്",
      brother:"സഹോദരൻ",sister:"സഹോദരി",husband:"ഭർത്താവ്",wife:"ഭാര്യ",son:"മകൻ",daughter:"മകൾ",grandfather:"മുത്തച്ഛൻ",grandmother:"മുത്തശ്ശി",
      doctor:"ഡോക്ടർ",teacher:"അദ്ധ്യാപകൻ",student:"വിദ്യാർത്ഥി",farmer:"കർഷകൻ",police:"പോലീസ്",
      country:"രാജ്യം",government:"സർക്കാർ",religion:"മതം",culture:"സംസ്കാരം",language:"ഭാഷ",education:"വിദ്യാഭ്യാസം",health:"ആരോഗ്യം",science:"ശാസ്ത്രം",
      today:"ഇന്ന്",yesterday:"ഇന്നലെ",tomorrow:"നാളെ",now:"ഇപ്പോൾ",always:"എപ്പോഴും",never:"ഒരിക്കലും",sometimes:"ചിലപ്പോൾ",
      yes:"അതെ",no:"ഇല്ല",please:"ദയവായി",thank:"നന്ദി",sorry:"ക്ഷമിക്കുക",hello:"നമസ്കാരം",
      kitchen:"അടുക്കള",garden:"തോട്ടം",market:"ചന്ത",hospital:"ആശുപത്രി",temple:"ക്ഷേത്രം",
      phone:"ഫോൺ",computer:"കമ്പ്യൂട്ടർ",car:"കാർ",train:"ട്രെയിൻ",
      courage:"ധൈര്യം",wisdom:"ജ്ഞാനം",patience:"ക്ഷമ",kindness:"ദയ",respect:"ആദരവ്",trust:"വിശ്വാസം",faith:"വിശ്വാസം",justice:"നീതി",freedom:"സ്വാതന്ത്ര്യം",beauty:"സൗന്ദര്യം",happiness:"സന്തോഷം",anger:"ദേഷ്യം",fear:"ഭയം",pride:"അഭിമാനം",joy:"ആനന്ദം",victory:"വിജയം",defeat:"പരാജയം",success:"വിജയം",failure:"പരാജയം",
      rice:"അരി",coconut:"തേങ്ങ",banana:"വാഴപ്പഴം",mango:"മാങ്ങ",village:"ഗ്രാമം",boat:"വഞ്ചി",beach:"കടൽത്തീരം",paddy:"നെൽ",elephant:"ആന",tiger:"കടുവ"
    }
  },

  ta: {
    name: "Tamil", flag: "🇮🇳", tier: "free", voice: "ta-IN",
    dict: {
      time:"நேரம்",year:"ஆண்டு",people:"மக்கள்",way:"வழி",day:"நாள்",man:"மனிதன்",woman:"பெண்",child:"குழந்தை",world:"உலகம்",life:"வாழ்க்கை",hand:"கை",place:"இடம்",home:"வீடு",water:"தண்ணீர்",room:"அறை",money:"பணம்",book:"புத்தகம்",eye:"கண்",word:"வார்த்தை",house:"வீடு",food:"உணவு",door:"கதவு",family:"குடும்பம்",city:"நகரம்",name:"பெயர்",game:"விளையாட்டு",body:"உடல்",school:"பள்ளி",morning:"காலை",night:"இரவு",friend:"நண்பன்",father:"தந்தை",mother:"அம்மா",work:"வேலை",power:"சக்தி",voice:"குரல்",road:"சாலை",
      good:"நல்ல",new:"புதிய",old:"பழைய",great:"சிறந்த",small:"சிறிய",young:"இளம்",important:"முக்கியம்",free:"சுதந்திரம்",strong:"வலிமை",true:"உண்மை",long:"நீண்ட",short:"குறுகிய",big:"பெரிய",beautiful:"அழகான",happy:"மகிழ்ச்சி",sad:"சோகம்",fast:"வேகம்",slow:"மெதுவாக",hot:"வெப்பம்",cold:"குளிர்",dark:"இருள்",light:"ஒளி",
      think:"சிந்தி",know:"தெரிய",see:"பார்",come:"வா",want:"வேண்டும்",find:"கண்டுபிடி",give:"கொடு",feel:"உணர்",take:"எடு",make:"செய்",go:"போ",say:"சொல்",get:"பெறு",use:"பயன்படுத்து",look:"பார்",tell:"சொல்",become:"ஆகு",leave:"விட்டு போ",put:"வை",keep:"வை",begin:"தொடங்கு",show:"காட்டு",hear:"கேள்",play:"விளையாடு",run:"ஓடு",move:"நகர்",live:"வாழ்",believe:"நம்பு",hold:"பிடி",bring:"கொண்டு வா",happen:"நடக்கும்",write:"எழுது",sit:"உட்கார்",stand:"நில்",lose:"இழக்க",pay:"பணம் கொடு",meet:"சந்திக்க",read:"படி",eat:"சாப்பிடு",walk:"நட",talk:"பேசு",learn:"கற்றுக்கொள்",help:"உதவி",try:"முயற்சி",buy:"வாங்கு",sell:"விற்கு",send:"அனுப்பு",
      sun:"சூரியன்",moon:"சந்திரன்",sky:"வானம்",tree:"மரம்",flower:"பூ",fire:"நெருப்பு",wind:"காற்று",rain:"மழை",mountain:"மலை",river:"ஆறு",sea:"கடல்",animal:"விலங்கு",dog:"நாய்",cat:"பூனை",bird:"பறவை",fish:"மீன்",
      love:"அன்பு",heart:"இதயம்",mind:"மனம்",soul:"ஆன்மா",dream:"கனவு",hope:"நம்பிக்கை",peace:"அமைதி",war:"போர்",truth:"உண்மை",right:"சரி",wrong:"தவறு",bad:"கெட்ட",
      one:"ஒன்று",two:"இரண்டு",three:"மூன்று",four:"நான்கு",five:"ஐந்து",six:"ஆறு",seven:"ஏழு",eight:"எட்டு",nine:"ஒன்பது",ten:"பத்து",hundred:"நூறு",
      red:"சிவப்பு",blue:"நீலம்",green:"பச்சை",yellow:"மஞ்சள்",white:"வெள்ளை",black:"கருப்பு",
      brother:"சகோதரன்",sister:"சகோதரி",husband:"கணவன்",wife:"மனைவி",son:"மகன்",daughter:"மகள்",grandfather:"தாத்தா",grandmother:"பாட்டி",
      doctor:"மருத்துவர்",teacher:"ஆசிரியர்",student:"மாணவன்",farmer:"விவசாயி",police:"காவலர்",
      country:"நாடு",government:"அரசு",religion:"மதம்",culture:"கலாச்சாரம்",language:"மொழி",education:"கல்வி",health:"ஆரோக்கியம்",science:"அறிவியல்",
      today:"இன்று",yesterday:"நேற்று",tomorrow:"நாளை",now:"இப்போது",always:"எப்போதும்",never:"ஒருபோதும்",sometimes:"சில நேரம்",
      yes:"ஆம்",no:"இல்லை",please:"தயவுசெய்து",thank:"நன்றி",sorry:"மன்னிக்கவும்",hello:"வணக்கம்",
      kitchen:"சமையலறை",garden:"தோட்டம்",market:"சந்தை",hospital:"மருத்துவமனை",temple:"கோயில்",
      phone:"தொலைபேசி",computer:"கணினி",car:"கார்",train:"ரயில்",
      courage:"தைரியம்",wisdom:"ஞானம்",patience:"பொறுமை",kindness:"கருணை",respect:"மரியாதை",trust:"நம்பிக்கை",justice:"நீதி",freedom:"சுதந்திரம்",beauty:"அழகு",happiness:"மகிழ்ச்சி",anger:"கோபம்",fear:"பயம்",pride:"பெருமை",joy:"மகிழ்வு",victory:"வெற்றி",defeat:"தோல்வி",success:"வெற்றி",failure:"தோல்வி",
      rice:"அரிசி",coconut:"தேங்காய்",banana:"வாழைப்பழம்",mango:"மாம்பழம்",village:"கிராமம்",boat:"படகு",beach:"கடற்கரை",elephant:"யானை",tiger:"புலி"
    }
  },

  ja: {
    name: "Japanese", flag: "🇯🇵", tier: "free", voice: "ja-JP",
    dict: {
      time:"時間",year:"年",people:"人々",way:"方法",day:"日",man:"男性",woman:"女性",child:"子供",world:"世界",life:"人生",hand:"手",place:"場所",home:"家",water:"水",room:"部屋",money:"お金",book:"本",eye:"目",word:"言葉",house:"家",food:"食べ物",door:"ドア",family:"家族",city:"都市",name:"名前",game:"ゲーム",body:"体",school:"学校",morning:"朝",night:"夜",friend:"友達",father:"父",mother:"母",work:"仕事",power:"力",voice:"声",road:"道",
      good:"良い",new:"新しい",old:"古い",great:"素晴らしい",small:"小さい",young:"若い",important:"重要",free:"自由",strong:"強い",true:"本当",long:"長い",short:"短い",big:"大きい",beautiful:"美しい",happy:"幸せ",sad:"悲しい",fast:"速い",slow:"遅い",hot:"熱い",cold:"冷たい",dark:"暗い",light:"明るい",
      think:"考える",know:"知る",see:"見る",come:"来る",want:"欲しい",find:"見つける",give:"あげる",feel:"感じる",take:"取る",make:"作る",go:"行く",say:"言う",get:"もらう",use:"使う",look:"見る",tell:"教える",become:"なる",leave:"去る",put:"置く",keep:"保つ",let:"させる",begin:"始める",show:"見せる",hear:"聞く",play:"遊ぶ",run:"走る",move:"動く",live:"生きる",believe:"信じる",hold:"持つ",bring:"持ってくる",happen:"起こる",write:"書く",sit:"座る",stand:"立つ",lose:"なくす",pay:"払う",meet:"会う",read:"読む",eat:"食べる",walk:"歩く",talk:"話す",learn:"学ぶ",help:"助ける",try:"試みる",buy:"買う",sell:"売る",send:"送る",
      sun:"太陽",moon:"月",sky:"空",tree:"木",flower:"花",fire:"火",wind:"風",rain:"雨",mountain:"山",river:"川",sea:"海",animal:"動物",dog:"犬",cat:"猫",bird:"鳥",fish:"魚",
      love:"愛",heart:"心",mind:"心",soul:"魂",dream:"夢",hope:"希望",peace:"平和",war:"戦争",truth:"真実",right:"正しい",wrong:"間違い",bad:"悪い",
      one:"一",two:"二",three:"三",four:"四",five:"五",six:"六",seven:"七",eight:"八",nine:"九",ten:"十",hundred:"百",thousand:"千",
      red:"赤",blue:"青",green:"緑",yellow:"黄色",white:"白",black:"黒",
      brother:"兄弟",sister:"姉妹",husband:"夫",wife:"妻",son:"息子",daughter:"娘",grandfather:"祖父",grandmother:"祖母",
      doctor:"医者",teacher:"先生",student:"学生",farmer:"農家",police:"警察",
      country:"国",government:"政府",religion:"宗教",culture:"文化",language:"言語",education:"教育",health:"健康",science:"科学",technology:"技術",
      today:"今日",yesterday:"昨日",tomorrow:"明日",now:"今",always:"いつも",never:"決して",sometimes:"時々",
      yes:"はい",no:"いいえ",please:"お願い",thank:"ありがとう",sorry:"ごめんなさい",hello:"こんにちは",
      kitchen:"台所",garden:"庭",market:"市場",hospital:"病院",temple:"寺",
      phone:"電話",computer:"コンピューター",car:"車",train:"電車",
      courage:"勇気",wisdom:"知恵",patience:"忍耐",kindness:"親切",respect:"尊重",trust:"信頼",faith:"信仰",justice:"正義",freedom:"自由",beauty:"美しさ",happiness:"幸福",sadness:"悲しみ",anger:"怒り",fear:"恐れ",pride:"誇り",joy:"喜び",victory:"勝利",defeat:"敗北",success:"成功",failure:"失敗"
    }
  },

  ko: {
    name: "Korean", flag: "🇰🇷", tier: "free", voice: "ko-KR",
    dict: {
      time:"시간",year:"년",people:"사람들",way:"방법",day:"날",man:"남자",woman:"여자",child:"아이",world:"세계",life:"삶",hand:"손",place:"장소",home:"집",water:"물",room:"방",money:"돈",book:"책",eye:"눈",word:"단어",house:"집",food:"음식",door:"문",family:"가족",city:"도시",name:"이름",game:"게임",body:"몸",school:"학교",morning:"아침",night:"밤",friend:"친구",father:"아버지",mother:"어머니",work:"일",power:"힘",voice:"목소리",road:"길",
      good:"좋은",new:"새로운",old:"오래된",great:"위대한",small:"작은",young:"젊은",important:"중요한",free:"자유로운",strong:"강한",true:"진실",long:"긴",short:"짧은",big:"큰",beautiful:"아름다운",happy:"행복한",sad:"슬픈",fast:"빠른",slow:"느린",hot:"뜨거운",cold:"차가운",dark:"어두운",light:"밝은",
      think:"생각하다",know:"알다",see:"보다",come:"오다",want:"원하다",find:"찾다",give:"주다",feel:"느끼다",take:"가져가다",make:"만들다",go:"가다",say:"말하다",get:"얻다",use:"사용하다",look:"보다",tell:"알려주다",become:"되다",leave:"떠나다",put:"놓다",keep:"유지하다",let:"허락하다",begin:"시작하다",show:"보여주다",hear:"듣다",play:"놀다",run:"달리다",move:"움직이다",live:"살다",believe:"믿다",hold:"잡다",bring:"가져오다",happen:"일어나다",write:"쓰다",sit:"앉다",stand:"서다",lose:"잃다",pay:"지불하다",meet:"만나다",read:"읽다",eat:"먹다",walk:"걷다",talk:"이야기하다",learn:"배우다",help:"돕다",try:"시도하다",buy:"사다",sell:"팔다",send:"보내다",
      sun:"태양",moon:"달",sky:"하늘",tree:"나무",flower:"꽃",fire:"불",wind:"바람",rain:"비",mountain:"산",river:"강",sea:"바다",animal:"동물",dog:"개",cat:"고양이",bird:"새",fish:"물고기",
      love:"사랑",heart:"마음",mind:"마음",soul:"영혼",dream:"꿈",hope:"희망",peace:"평화",war:"전쟁",truth:"진실",right:"옳은",wrong:"틀린",bad:"나쁜",
      one:"하나",two:"둘",three:"셋",four:"넷",five:"다섯",six:"여섯",seven:"일곱",eight:"여덟",nine:"아홉",ten:"열",hundred:"백",thousand:"천",
      red:"빨간",blue:"파란",green:"초록",yellow:"노란",white:"흰",black:"검은",
      brother:"형제",sister:"자매",husband:"남편",wife:"아내",son:"아들",daughter:"딸",grandfather:"할아버지",grandmother:"할머니",
      doctor:"의사",teacher:"선생님",student:"학생",farmer:"농부",police:"경찰",
      country:"나라",government:"정부",religion:"종교",culture:"문화",language:"언어",education:"교육",health:"건강",science:"과학",technology:"기술",
      today:"오늘",yesterday:"어제",tomorrow:"내일",now:"지금",always:"항상",never:"절대",sometimes:"가끔",
      yes:"네",no:"아니오",please:"제발",thank:"감사합니다",sorry:"미안합니다",hello:"안녕하세요",
      kitchen:"부엌",garden:"정원",market:"시장",hospital:"병원",temple:"사원",
      phone:"전화",computer:"컴퓨터",car:"자동차",train:"기차",
      courage:"용기",wisdom:"지혜",patience:"인내",kindness:"친절",respect:"존중",trust:"신뢰",faith:"믿음",justice:"정의",freedom:"자유",beauty:"아름다움",happiness:"행복",sadness:"슬픔",anger:"화",fear:"두려움",pride:"자부심",joy:"기쁨",victory:"승리",defeat:"패배",success:"성공",failure:"실패"
    }
  },

  ar: {
    name: "Arabic", flag: "🇸🇦", tier: "free", voice: "ar-SA",
    dict: {
      time:"وقت",year:"سنة",people:"ناس",way:"طريق",day:"يوم",man:"رجل",woman:"امرأة",child:"طفل",world:"عالم",life:"حياة",hand:"يد",place:"مكان",home:"بيت",water:"ماء",room:"غرفة",money:"مال",book:"كتاب",eye:"عين",word:"كلمة",house:"منزل",food:"طعام",door:"باب",family:"عائلة",city:"مدينة",name:"اسم",game:"لعبة",body:"جسم",school:"مدرسة",morning:"صباح",night:"ليل",friend:"صديق",father:"أب",mother:"أم",work:"عمل",power:"قوة",voice:"صوت",road:"طريق",
      good:"جيد",new:"جديد",old:"قديم",great:"عظيم",small:"صغير",young:"شاب",important:"مهم",free:"حر",strong:"قوي",true:"صحيح",long:"طويل",short:"قصير",big:"كبير",beautiful:"جميل",happy:"سعيد",sad:"حزين",fast:"سريع",slow:"بطيء",hot:"حار",cold:"بارد",dark:"مظلم",light:"مضيء",
      think:"يفكر",know:"يعرف",see:"يرى",come:"يأتي",want:"يريد",find:"يجد",give:"يعطي",feel:"يشعر",take:"يأخذ",make:"يصنع",go:"يذهب",say:"يقول",get:"يحصل",use:"يستخدم",look:"ينظر",tell:"يخبر",become:"يصبح",leave:"يغادر",put:"يضع",keep:"يحافظ",begin:"يبدأ",show:"يُظهر",hear:"يسمع",play:"يلعب",run:"يركض",move:"يتحرك",live:"يعيش",believe:"يؤمن",hold:"يمسك",bring:"يحضر",happen:"يحدث",write:"يكتب",sit:"يجلس",stand:"يقف",lose:"يخسر",pay:"يدفع",meet:"يقابل",read:"يقرأ",eat:"يأكل",walk:"يمشي",talk:"يتحدث",learn:"يتعلم",help:"يساعد",try:"يحاول",buy:"يشتري",sell:"يبيع",send:"يرسل",
      sun:"شمس",moon:"قمر",sky:"سماء",tree:"شجرة",flower:"زهرة",fire:"نار",wind:"ريح",rain:"مطر",mountain:"جبل",river:"نهر",sea:"بحر",animal:"حيوان",dog:"كلب",cat:"قطة",bird:"طائر",fish:"سمكة",
      love:"حب",heart:"قلب",mind:"عقل",soul:"روح",dream:"حلم",hope:"أمل",peace:"سلام",war:"حرب",truth:"حقيقة",right:"صحيح",wrong:"خطأ",bad:"سيء",
      one:"واحد",two:"اثنان",three:"ثلاثة",four:"أربعة",five:"خمسة",six:"ستة",seven:"سبعة",eight:"ثمانية",nine:"تسعة",ten:"عشرة",hundred:"مئة",thousand:"ألف",
      red:"أحمر",blue:"أزرق",green:"أخضر",yellow:"أصفر",white:"أبيض",black:"أسود",
      brother:"أخ",sister:"أخت",husband:"زوج",wife:"زوجة",son:"ابن",daughter:"ابنة",grandfather:"جد",grandmother:"جدة",
      doctor:"طبيب",teacher:"معلم",student:"طالب",farmer:"مزارع",police:"شرطة",
      country:"بلد",government:"حكومة",religion:"دين",culture:"ثقافة",language:"لغة",education:"تعليم",health:"صحة",science:"علم",technology:"تكنولوجيا",
      today:"اليوم",yesterday:"أمس",tomorrow:"غداً",now:"الآن",always:"دائماً",never:"أبداً",sometimes:"أحياناً",
      yes:"نعم",no:"لا",please:"من فضلك",thank:"شكراً",sorry:"آسف",hello:"مرحبا",
      kitchen:"مطبخ",garden:"حديقة",market:"سوق",hospital:"مستشفى",mosque:"مسجد",
      phone:"هاتف",computer:"كمبيوتر",car:"سيارة",train:"قطار",
      courage:"شجاعة",wisdom:"حكمة",patience:"صبر",kindness:"لطف",respect:"احترام",trust:"ثقة",faith:"إيمان",justice:"عدالة",freedom:"حرية",beauty:"جمال",happiness:"سعادة",sadness:"حزن",anger:"غضب",fear:"خوف",pride:"فخر",joy:"فرح",victory:"انتصار",defeat:"هزيمة",success:"نجاح",failure:"فشل"
    }
  },

  ru: {
    name: "Russian", flag: "🇷🇺", tier: "free", voice: "ru-RU",
    dict: {
      time:"время",year:"год",people:"люди",way:"путь",day:"день",man:"мужчина",woman:"женщина",child:"ребёнок",world:"мир",life:"жизнь",hand:"рука",place:"место",home:"дом",water:"вода",room:"комната",money:"деньги",book:"книга",eye:"глаз",word:"слово",house:"дом",food:"еда",door:"дверь",family:"семья",city:"город",name:"имя",game:"игра",body:"тело",school:"школа",morning:"утро",night:"ночь",friend:"друг",father:"отец",mother:"мать",work:"работа",power:"сила",voice:"голос",road:"дорога",
      good:"хороший",new:"новый",old:"старый",great:"великий",small:"маленький",young:"молодой",important:"важный",free:"свободный",strong:"сильный",true:"правда",long:"длинный",short:"короткий",big:"большой",beautiful:"красивый",happy:"счастливый",sad:"грустный",fast:"быстрый",slow:"медленный",hot:"горячий",cold:"холодный",dark:"тёмный",light:"светлый",
      think:"думать",know:"знать",see:"видеть",come:"приходить",want:"хотеть",find:"найти",give:"давать",feel:"чувствовать",take:"брать",make:"делать",go:"идти",say:"говорить",get:"получать",use:"использовать",look:"смотреть",tell:"рассказывать",become:"стать",leave:"уходить",put:"класть",keep:"хранить",let:"позволять",begin:"начинать",show:"показывать",hear:"слышать",play:"играть",run:"бежать",move:"двигаться",live:"жить",believe:"верить",hold:"держать",bring:"приносить",happen:"происходить",write:"писать",sit:"сидеть",stand:"стоять",lose:"терять",pay:"платить",meet:"встречать",read:"читать",eat:"есть",walk:"ходить",talk:"разговаривать",learn:"учиться",help:"помогать",try:"пробовать",buy:"покупать",sell:"продавать",send:"отправлять",
      sun:"солнце",moon:"луна",sky:"небо",tree:"дерево",flower:"цветок",fire:"огонь",wind:"ветер",rain:"дождь",mountain:"гора",river:"река",sea:"море",animal:"животное",dog:"собака",cat:"кошка",bird:"птица",fish:"рыба",
      love:"любовь",heart:"сердце",mind:"разум",soul:"душа",dream:"мечта",hope:"надежда",peace:"мир",war:"война",truth:"правда",right:"правильный",wrong:"неправильный",bad:"плохой",
      one:"один",two:"два",three:"три",four:"четыре",five:"пять",six:"шесть",seven:"семь",eight:"восемь",nine:"девять",ten:"десять",hundred:"сто",thousand:"тысяча",
      red:"красный",blue:"синий",green:"зелёный",yellow:"жёлтый",white:"белый",black:"чёрный",
      brother:"брат",sister:"сестра",husband:"муж",wife:"жена",son:"сын",daughter:"дочь",grandfather:"дедушка",grandmother:"бабушка",
      doctor:"врач",teacher:"учитель",student:"студент",farmer:"фермер",police:"полиция",
      country:"страна",government:"правительство",religion:"религия",culture:"культура",language:"язык",education:"образование",health:"здоровье",science:"наука",technology:"технология",
      today:"сегодня",yesterday:"вчера",tomorrow:"завтра",now:"сейчас",always:"всегда",never:"никогда",sometimes:"иногда",
      yes:"да",no:"нет",please:"пожалуйста",thank:"спасибо",sorry:"извините",hello:"привет",
      kitchen:"кухня",garden:"сад",market:"рынок",hospital:"больница",church:"церковь",
      phone:"телефон",computer:"компьютер",car:"машина",train:"поезд",
      courage:"смелость",wisdom:"мудрость",patience:"терпение",kindness:"доброта",respect:"уважение",trust:"доверие",faith:"вера",justice:"справедливость",freedom:"свобода",beauty:"красота",happiness:"счастье",sadness:"грусть",anger:"злость",fear:"страх",pride:"гордость",joy:"радость",victory:"победа",defeat:"поражение",success:"успех",failure:"неудача"
    }
  },

  zh: {
    name: "Chinese", flag: "🇨🇳", tier: "free", voice: "zh-CN",
    dict: {
      time:"时间",year:"年",people:"人们",way:"方式",day:"天",man:"男人",woman:"女人",child:"孩子",world:"世界",life:"生活",hand:"手",place:"地方",home:"家",water:"水",room:"房间",money:"钱",book:"书",eye:"眼睛",word:"词",house:"房子",food:"食物",door:"门",family:"家庭",city:"城市",name:"名字",game:"游戏",body:"身体",school:"学校",morning:"早晨",night:"夜晚",friend:"朋友",father:"父亲",mother:"母亲",work:"工作",power:"力量",voice:"声音",road:"路",
      good:"好",new:"新",old:"旧",great:"伟大",small:"小",young:"年轻",important:"重要",free:"自由",strong:"强",true:"真",long:"长",short:"短",big:"大",beautiful:"美丽",happy:"快乐",sad:"悲伤",fast:"快",slow:"慢",hot:"热",cold:"冷",dark:"黑暗",light:"光明",
      think:"思考",know:"知道",see:"看",come:"来",want:"想要",find:"找到",give:"给",feel:"感觉",take:"拿",make:"做",go:"去",say:"说",get:"得到",use:"使用",look:"看",tell:"告诉",become:"成为",leave:"离开",put:"放",keep:"保持",let:"让",begin:"开始",show:"展示",hear:"听",play:"玩",run:"跑",move:"移动",live:"生活",believe:"相信",hold:"握住",bring:"带来",happen:"发生",write:"写",sit:"坐",stand:"站",lose:"失去",pay:"支付",meet:"见面",read:"读",eat:"吃",walk:"走路",talk:"说话",learn:"学习",help:"帮助",try:"尝试",buy:"买",sell:"卖",send:"发送",
      sun:"太阳",moon:"月亮",sky:"天空",tree:"树",flower:"花",fire:"火",wind:"风",rain:"雨",mountain:"山",river:"河",sea:"海",animal:"动物",dog:"狗",cat:"猫",bird:"鸟",fish:"鱼",
      love:"爱",heart:"心",mind:"思想",soul:"灵魂",dream:"梦想",hope:"希望",peace:"和平",war:"战争",truth:"真相",right:"对",wrong:"错",bad:"坏",
      one:"一",two:"二",three:"三",four:"四",five:"五",six:"六",seven:"七",eight:"八",nine:"九",ten:"十",hundred:"百",thousand:"千",
      red:"红色",blue:"蓝色",green:"绿色",yellow:"黄色",white:"白色",black:"黑色",
      brother:"兄弟",sister:"姐妹",husband:"丈夫",wife:"妻子",son:"儿子",daughter:"女儿",grandfather:"祖父",grandmother:"祖母",
      doctor:"医生",teacher:"老师",student:"学生",farmer:"农民",police:"警察",
      country:"国家",government:"政府",religion:"宗教",culture:"文化",language:"语言",education:"教育",health:"健康",science:"科学",technology:"技术",
      today:"今天",yesterday:"昨天",tomorrow:"明天",now:"现在",always:"总是",never:"从不",sometimes:"有时",
      yes:"是",no:"否",please:"请",thank:"谢谢",sorry:"对不起",hello:"你好",
      kitchen:"厨房",garden:"花园",market:"市场",hospital:"医院",temple:"庙",
      phone:"电话",computer:"电脑",car:"汽车",train:"火车",
      courage:"勇气",wisdom:"智慧",patience:"耐心",kindness:"善良",respect:"尊重",trust:"信任",faith:"信仰",justice:"正义",freedom:"自由",beauty:"美丽",happiness:"幸福",sadness:"悲伤",anger:"愤怒",fear:"恐惧",pride:"骄傲",joy:"喜悦",victory:"胜利",defeat:"失败",success:"成功",failure:"失败"
    }
  },

  nl: {
    name: "Dutch", flag: "🇳🇱", tier: "free", voice: "nl-NL",
    dict: {
      time:"tijd",year:"jaar",people:"mensen",way:"weg",day:"dag",man:"man",woman:"vrouw",child:"kind",world:"wereld",life:"leven",hand:"hand",place:"plek",home:"thuis",water:"water",room:"kamer",money:"geld",book:"boek",eye:"oog",word:"woord",house:"huis",food:"eten",door:"deur",family:"familie",city:"stad",name:"naam",game:"spel",body:"lichaam",school:"school",morning:"ochtend",night:"nacht",friend:"vriend",father:"vader",mother:"moeder",work:"werk",power:"macht",voice:"stem",road:"weg",
      good:"goed",new:"nieuw",old:"oud",great:"groot",small:"klein",young:"jong",important:"belangrijk",free:"vrij",strong:"sterk",true:"waar",long:"lang",short:"kort",big:"groot",beautiful:"mooi",happy:"blij",sad:"verdrietig",fast:"snel",slow:"langzaam",hot:"heet",cold:"koud",dark:"donker",light:"licht",
      think:"denken",know:"weten",see:"zien",come:"komen",want:"willen",find:"vinden",give:"geven",feel:"voelen",take:"nemen",make:"maken",go:"gaan",say:"zeggen",get:"krijgen",use:"gebruiken",look:"kijken",tell:"vertellen",become:"worden",leave:"vertrekken",put:"zetten",keep:"houden",begin:"beginnen",show:"tonen",hear:"horen",play:"spelen",run:"rennen",move:"bewegen",live:"leven",believe:"geloven",hold:"vasthouden",bring:"brengen",happen:"gebeuren",write:"schrijven",sit:"zitten",stand:"staan",lose:"verliezen",pay:"betalen",meet:"ontmoeten",read:"lezen",eat:"eten",walk:"lopen",talk:"praten",learn:"leren",help:"helpen",try:"proberen",buy:"kopen",sell:"verkopen",send:"sturen",
      sun:"zon",moon:"maan",sky:"lucht",tree:"boom",flower:"bloem",fire:"vuur",wind:"wind",rain:"regen",mountain:"berg",river:"rivier",sea:"zee",animal:"dier",dog:"hond",cat:"kat",bird:"vogel",fish:"vis",
      love:"liefde",heart:"hart",mind:"geest",soul:"ziel",dream:"droom",hope:"hoop",peace:"vrede",war:"oorlog",truth:"waarheid",right:"juist",wrong:"fout",bad:"slecht",
      one:"één",two:"twee",three:"drie",four:"vier",five:"vijf",six:"zes",seven:"zeven",eight:"acht",nine:"negen",ten:"tien",hundred:"honderd",thousand:"duizend",
      red:"rood",blue:"blauw",green:"groen",yellow:"geel",white:"wit",black:"zwart",
      brother:"broer",sister:"zus",husband:"man",wife:"vrouw",son:"zoon",daughter:"dochter",grandfather:"grootvader",grandmother:"grootmoeder",
      doctor:"dokter",teacher:"leraar",student:"student",farmer:"boer",police:"politie",
      country:"land",government:"regering",religion:"religie",culture:"cultuur",language:"taal",education:"onderwijs",health:"gezondheid",science:"wetenschap",technology:"technologie",
      today:"vandaag",yesterday:"gisteren",tomorrow:"morgen",now:"nu",always:"altijd",never:"nooit",sometimes:"soms",
      yes:"ja",no:"nee",please:"alsjeblieft",thank:"dank je",sorry:"sorry",hello:"hallo",
      kitchen:"keuken",garden:"tuin",market:"markt",hospital:"ziekenhuis",church:"kerk",
      phone:"telefoon",computer:"computer",car:"auto",train:"trein",
      courage:"moed",wisdom:"wijsheid",patience:"geduld",kindness:"vriendelijkheid",respect:"respect",trust:"vertrouwen",faith:"geloof",justice:"gerechtigheid",freedom:"vrijheid",beauty:"schoonheid",happiness:"geluk",sadness:"verdriet",anger:"boosheid",fear:"angst",pride:"trots",joy:"vreugde",victory:"overwinning",defeat:"nederlaag",success:"succes",failure:"mislukking"
    }
  },

  tr: {
    name: "Turkish", flag: "🇹🇷", tier: "free", voice: "tr-TR",
    dict: {
      time:"zaman",year:"yıl",people:"insanlar",way:"yol",day:"gün",man:"adam",woman:"kadın",child:"çocuk",world:"dünya",life:"hayat",hand:"el",place:"yer",home:"ev",water:"su",room:"oda",money:"para",book:"kitap",eye:"göz",word:"kelime",house:"ev",food:"yemek",door:"kapı",family:"aile",city:"şehir",name:"isim",game:"oyun",body:"vücut",school:"okul",morning:"sabah",night:"gece",friend:"arkadaş",father:"baba",mother:"anne",work:"iş",power:"güç",voice:"ses",road:"yol",
      good:"iyi",new:"yeni",old:"eski",great:"büyük",small:"küçük",young:"genç",important:"önemli",free:"özgür",strong:"güçlü",true:"doğru",long:"uzun",short:"kısa",big:"büyük",beautiful:"güzel",happy:"mutlu",sad:"üzgün",fast:"hızlı",slow:"yavaş",hot:"sıcak",cold:"soğuk",dark:"karanlık",light:"aydınlık",
      think:"düşünmek",know:"bilmek",see:"görmek",come:"gelmek",want:"istemek",find:"bulmak",give:"vermek",feel:"hissetmek",take:"almak",make:"yapmak",go:"gitmek",say:"söylemek",get:"almak",use:"kullanmak",look:"bakmak",tell:"anlatmak",become:"olmak",leave:"ayrılmak",put:"koymak",keep:"tutmak",begin:"başlamak",show:"göstermek",hear:"duymak",play:"oynamak",run:"koşmak",move:"hareket etmek",live:"yaşamak",believe:"inanmak",hold:"tutmak",bring:"getirmek",happen:"olmak",write:"yazmak",sit:"oturmak",stand:"ayakta durmak",lose:"kaybetmek",pay:"ödemek",meet:"buluşmak",read:"okumak",eat:"yemek",walk:"yürümek",talk:"konuşmak",learn:"öğrenmek",help:"yardım etmek",try:"denemek",buy:"satın almak",sell:"satmak",send:"göndermek",
      sun:"güneş",moon:"ay",sky:"gökyüzü",tree:"ağaç",flower:"çiçek",fire:"ateş",wind:"rüzgar",rain:"yağmur",mountain:"dağ",river:"nehir",sea:"deniz",animal:"hayvan",dog:"köpek",cat:"kedi",bird:"kuş",fish:"balık",
      love:"aşk",heart:"kalp",mind:"zihin",soul:"ruh",dream:"rüya",hope:"umut",peace:"barış",war:"savaş",truth:"gerçek",right:"doğru",wrong:"yanlış",bad:"kötü",
      one:"bir",two:"iki",three:"üç",four:"dört",five:"beş",six:"altı",seven:"yedi",eight:"sekiz",nine:"dokuz",ten:"on",hundred:"yüz",thousand:"bin",
      red:"kırmızı",blue:"mavi",green:"yeşil",yellow:"sarı",white:"beyaz",black:"siyah",
      brother:"erkek kardeş",sister:"kız kardeş",husband:"koca",wife:"karı",son:"oğul",daughter:"kız",grandfather:"büyükbaba",grandmother:"büyükanne",
      doctor:"doktor",teacher:"öğretmen",student:"öğrenci",farmer:"çiftçi",police:"polis",
      country:"ülke",government:"hükümet",religion:"din",culture:"kültür",language:"dil",education:"eğitim",health:"sağlık",science:"bilim",technology:"teknoloji",
      today:"bugün",yesterday:"dün",tomorrow:"yarın",now:"şimdi",always:"her zaman",never:"asla",sometimes:"bazen",
      yes:"evet",no:"hayır",please:"lütfen",thank:"teşekkür",sorry:"özür",hello:"merhaba",
      kitchen:"mutfak",garden:"bahçe",market:"pazar",hospital:"hastane",mosque:"cami",
      phone:"telefon",computer:"bilgisayar",car:"araba",train:"tren",
      courage:"cesaret",wisdom:"bilgelik",patience:"sabır",kindness:"nezaket",respect:"saygı",trust:"güven",faith:"inanç",justice:"adalet",freedom:"özgürlük",beauty:"güzellik",happiness:"mutluluk",sadness:"üzüntü",anger:"öfke",fear:"korku",pride:"gurur",joy:"sevinç",victory:"zafer",defeat:"yenilgi",success:"başarı",failure:"başarısızlık"
    }
  },

  // ── PREMIUM LANGUAGES (35 more) ──────────────────────────────────────────
  pl: { name:"Polish", flag:"🇵🇱", tier:"premium", voice:"pl-PL", dict:{time:"czas",year:"rok",day:"dzień",world:"świat",life:"życie",home:"dom",water:"woda",food:"jedzenie",family:"rodzina",friend:"przyjaciel",work:"praca",good:"dobry",new:"nowy",old:"stary",think:"myśleć",know:"wiedzieć",see:"widzieć",give:"dawać",love:"miłość",city:"miasto",name:"imię",book:"książka",school:"szkoła",morning:"rano",night:"noc",man:"mężczyzna",woman:"kobieta",child:"dziecko",hand:"ręka",eye:"oko",heart:"serce",sun:"słońce",moon:"księżyc",tree:"drzewo",dog:"pies",cat:"kot",red:"czerwony",blue:"niebieski",green:"zielony",yes:"tak",no:"nie",hello:"cześć",thank:"dziękuję",sorry:"przepraszam",beautiful:"piękny",happy:"szczęśliwy",sad:"smutny",strong:"silny",peace:"pokój",war:"wojna",truth:"prawda",hope:"nadzieja",dream:"marzenie",country:"kraj",language:"język",health:"zdrowie",money:"pieniądze",door:"drzwi",road:"droga",brother:"brat",sister:"siostra",father:"ojciec",mother:"matka"} },
  sv: { name:"Swedish", flag:"🇸🇪", tier:"premium", voice:"sv-SE", dict:{time:"tid",year:"år",day:"dag",world:"värld",life:"liv",home:"hem",water:"vatten",food:"mat",family:"familj",friend:"vän",work:"arbete",good:"bra",new:"ny",old:"gammal",think:"tänka",know:"veta",see:"se",give:"ge",love:"kärlek",city:"stad",name:"namn",book:"bok",school:"skola",morning:"morgon",night:"natt",man:"man",woman:"kvinna",child:"barn",hand:"hand",eye:"öga",heart:"hjärta",sun:"sol",moon:"måne",tree:"träd",dog:"hund",cat:"katt",red:"röd",blue:"blå",green:"grön",yes:"ja",no:"nej",hello:"hej",thank:"tack",sorry:"förlåt",beautiful:"vacker",happy:"lycklig",sad:"ledsen",strong:"stark",peace:"fred",war:"krig",truth:"sanning",hope:"hopp",dream:"dröm",country:"land",language:"språk",health:"hälsa",money:"pengar",door:"dörr",road:"väg",brother:"bror",sister:"syster",father:"far",mother:"mor"} },
  no: { name:"Norwegian", flag:"🇳🇴", tier:"premium", voice:"no-NO", dict:{time:"tid",year:"år",day:"dag",world:"verden",life:"liv",home:"hjem",water:"vann",food:"mat",family:"familie",friend:"venn",work:"arbeid",good:"bra",new:"ny",old:"gammel",think:"tenke",know:"vite",see:"se",give:"gi",love:"kjærlighet",city:"by",name:"navn",book:"bok",school:"skole",morning:"morgen",night:"natt",man:"mann",woman:"kvinne",child:"barn",hand:"hånd",eye:"øye",heart:"hjerte",sun:"sol",moon:"måne",tree:"tre",dog:"hund",cat:"katt",red:"rød",blue:"blå",green:"grønn",yes:"ja",no:"nei",hello:"hei",thank:"takk",sorry:"beklager",beautiful:"vakker",happy:"lykkelig",sad:"trist",strong:"sterk",peace:"fred",war:"krig",truth:"sannhet",hope:"håp",dream:"drøm",country:"land",language:"språk",health:"helse",money:"penger",door:"dør",road:"vei",brother:"bror",sister:"søster",father:"far",mother:"mor"} },
  da: { name:"Danish", flag:"🇩🇰", tier:"premium", voice:"da-DK", dict:{time:"tid",year:"år",day:"dag",world:"verden",life:"liv",home:"hjem",water:"vand",food:"mad",family:"familie",friend:"ven",work:"arbejde",good:"god",new:"ny",old:"gammel",think:"tænke",know:"vide",see:"se",give:"give",love:"kærlighed",city:"by",name:"navn",book:"bog",school:"skole",morning:"morgen",night:"nat",man:"mand",woman:"kvinde",child:"barn",hand:"hånd",eye:"øje",heart:"hjerte",sun:"sol",moon:"måne",tree:"træ",dog:"hund",cat:"kat",red:"rød",blue:"blå",green:"grøn",yes:"ja",no:"nej",hello:"hej",thank:"tak",sorry:"undskyld",beautiful:"smuk",happy:"lykkelig",sad:"trist",strong:"stærk",peace:"fred",war:"krig",truth:"sandhed",hope:"håb",dream:"drøm",country:"land",language:"sprog",health:"helbred",money:"penge",door:"dør",road:"vej",brother:"bror",sister:"søster",father:"far",mother:"mor"} },
  fi: { name:"Finnish", flag:"🇫🇮", tier:"premium", voice:"fi-FI", dict:{time:"aika",year:"vuosi",day:"päivä",world:"maailma",life:"elämä",home:"koti",water:"vesi",food:"ruoka",family:"perhe",friend:"ystävä",work:"työ",good:"hyvä",new:"uusi",old:"vanha",think:"ajatella",know:"tietää",see:"nähdä",give:"antaa",love:"rakkaus",city:"kaupunki",name:"nimi",book:"kirja",school:"koulu",morning:"aamu",night:"yö",man:"mies",woman:"nainen",child:"lapsi",hand:"käsi",eye:"silmä",heart:"sydän",sun:"aurinko",moon:"kuu",tree:"puu",dog:"koira",cat:"kissa",red:"punainen",blue:"sininen",green:"vihreä",yes:"kyllä",no:"ei",hello:"hei",thank:"kiitos",sorry:"anteeksi",beautiful:"kaunis",happy:"onnellinen",sad:"surullinen",strong:"vahva",peace:"rauha",war:"sota",truth:"totuus",hope:"toivo",dream:"unelma",country:"maa",language:"kieli",health:"terveys",money:"raha",door:"ovi",road:"tie",brother:"veli",sister:"sisar",father:"isä",mother:"äiti"} },
  el: { name:"Greek", flag:"🇬🇷", tier:"premium", voice:"el-GR", dict:{time:"χρόνος",year:"χρόνια",day:"μέρα",world:"κόσμος",life:"ζωή",home:"σπίτι",water:"νερό",food:"φαγητό",family:"οικογένεια",friend:"φίλος",work:"δουλειά",good:"καλό",new:"νέο",old:"παλιό",love:"αγάπη",city:"πόλη",name:"όνομα",book:"βιβλίο",school:"σχολείο",morning:"πρωί",night:"νύχτα",man:"άντρας",woman:"γυναίκα",child:"παιδί",hand:"χέρι",eye:"μάτι",heart:"καρδιά",sun:"ήλιος",moon:"φεγγάρι",tree:"δέντρο",dog:"σκύλος",cat:"γάτα",red:"κόκκινο",blue:"μπλε",green:"πράσινο",yes:"ναι",no:"όχι",hello:"γεια",thank:"ευχαριστώ",sorry:"συγγνώμη",beautiful:"όμορφος",happy:"χαρούμενος",sad:"λυπημένος",strong:"δυνατός",peace:"ειρήνη",war:"πόλεμος",truth:"αλήθεια",hope:"ελπίδα",dream:"όνειρο",country:"χώρα",language:"γλώσσα",health:"υγεία",money:"χρήματα",door:"πόρτα",road:"δρόμος",brother:"αδερφός",sister:"αδερφή",father:"πατέρας",mother:"μητέρα"} },
  he: { name:"Hebrew", flag:"🇮🇱", tier:"premium", voice:"he-IL", dict:{time:"זמן",year:"שנה",day:"יום",world:"עולם",life:"חיים",home:"בית",water:"מים",food:"אוכל",family:"משפחה",friend:"חבר",work:"עבודה",good:"טוב",new:"חדש",old:"ישן",love:"אהבה",city:"עיר",name:"שם",book:"ספר",school:"בית ספר",morning:"בוקר",night:"לילה",man:"גבר",woman:"אישה",child:"ילד",hand:"יד",eye:"עין",heart:"לב",sun:"שמש",moon:"ירח",tree:"עץ",dog:"כלב",cat:"חתול",red:"אדום",blue:"כחול",green:"ירוק",yes:"כן",no:"לא",hello:"שלום",thank:"תודה",sorry:"סליחה",beautiful:"יפה",happy:"שמח",sad:"עצוב",strong:"חזק",peace:"שלום",war:"מלחמה",truth:"אמת",hope:"תקווה",dream:"חלום",country:"מדינה",language:"שפה",health:"בריאות",money:"כסף",door:"דלת",road:"דרך",brother:"אח",sister:"אחות",father:"אב",mother:"אמא"} },
  th: { name:"Thai", flag:"🇹🇭", tier:"premium", voice:"th-TH", dict:{time:"เวลา",year:"ปี",day:"วัน",world:"โลก",life:"ชีวิต",home:"บ้าน",water:"น้ำ",food:"อาหาร",family:"ครอบครัว",friend:"เพื่อน",work:"งาน",good:"ดี",new:"ใหม่",old:"เก่า",love:"รัก",city:"เมือง",name:"ชื่อ",book:"หนังสือ",school:"โรงเรียน",morning:"เช้า",night:"กลางคืน",man:"ผู้ชาย",woman:"ผู้หญิง",child:"เด็ก",hand:"มือ",eye:"ตา",heart:"ใจ",sun:"ดวงอาทิตย์",moon:"ดวงจันทร์",tree:"ต้นไม้",dog:"หมา",cat:"แมว",red:"แดง",blue:"น้ำเงิน",green:"เขียว",yes:"ใช่",no:"ไม่",hello:"สวัสดี",thank:"ขอบคุณ",sorry:"ขอโทษ",beautiful:"สวยงาม",happy:"มีความสุข",sad:"เศร้า",strong:"แข็งแกร่ง",peace:"สันติภาพ",war:"สงคราม",truth:"ความจริง",hope:"ความหวัง",dream:"ความฝัน",country:"ประเทศ",language:"ภาษา",health:"สุขภาพ",money:"เงิน",door:"ประตู",road:"ถนน",brother:"พี่ชาย",sister:"พี่สาว",father:"พ่อ",mother:"แม่"} },
  vi: { name:"Vietnamese", flag:"🇻🇳", tier:"premium", voice:"vi-VN", dict:{time:"thời gian",year:"năm",day:"ngày",world:"thế giới",life:"cuộc sống",home:"nhà",water:"nước",food:"thức ăn",family:"gia đình",friend:"bạn bè",work:"công việc",good:"tốt",new:"mới",old:"cũ",love:"tình yêu",city:"thành phố",name:"tên",book:"sách",school:"trường",morning:"buổi sáng",night:"ban đêm",man:"đàn ông",woman:"phụ nữ",child:"đứa trẻ",hand:"bàn tay",eye:"mắt",heart:"trái tim",sun:"mặt trời",moon:"mặt trăng",tree:"cây",dog:"chó",cat:"mèo",red:"đỏ",blue:"xanh lam",green:"xanh lá",yes:"vâng",no:"không",hello:"xin chào",thank:"cảm ơn",sorry:"xin lỗi",beautiful:"đẹp",happy:"vui vẻ",sad:"buồn",strong:"mạnh mẽ",peace:"hòa bình",war:"chiến tranh",truth:"sự thật",hope:"hy vọng",dream:"giấc mơ",country:"đất nước",language:"ngôn ngữ",health:"sức khỏe",money:"tiền",door:"cửa",road:"đường",brother:"anh trai",sister:"chị gái",father:"cha",mother:"mẹ"} },
  id: { name:"Indonesian", flag:"🇮🇩", tier:"premium", voice:"id-ID", dict:{time:"waktu",year:"tahun",day:"hari",world:"dunia",life:"kehidupan",home:"rumah",water:"air",food:"makanan",family:"keluarga",friend:"teman",work:"kerja",good:"baik",new:"baru",old:"tua",love:"cinta",city:"kota",name:"nama",book:"buku",school:"sekolah",morning:"pagi",night:"malam",man:"pria",woman:"wanita",child:"anak",hand:"tangan",eye:"mata",heart:"hati",sun:"matahari",moon:"bulan",tree:"pohon",dog:"anjing",cat:"kucing",red:"merah",blue:"biru",green:"hijau",yes:"ya",no:"tidak",hello:"halo",thank:"terima kasih",sorry:"maaf",beautiful:"cantik",happy:"bahagia",sad:"sedih",strong:"kuat",peace:"damai",war:"perang",truth:"kebenaran",hope:"harapan",dream:"mimpi",country:"negara",language:"bahasa",health:"kesehatan",money:"uang",door:"pintu",road:"jalan",brother:"kakak",sister:"adik",father:"ayah",mother:"ibu"} },
  ms: { name:"Malay", flag:"🇲🇾", tier:"premium", voice:"ms-MY", dict:{time:"masa",year:"tahun",day:"hari",world:"dunia",life:"kehidupan",home:"rumah",water:"air",food:"makanan",family:"keluarga",friend:"kawan",work:"kerja",good:"baik",new:"baru",old:"lama",love:"cinta",city:"bandar",name:"nama",book:"buku",school:"sekolah",morning:"pagi",night:"malam",man:"lelaki",woman:"perempuan",child:"kanak-kanak",hand:"tangan",eye:"mata",heart:"hati",sun:"matahari",moon:"bulan",tree:"pokok",dog:"anjing",cat:"kucing",red:"merah",blue:"biru",green:"hijau",yes:"ya",no:"tidak",hello:"helo",thank:"terima kasih",sorry:"maaf",beautiful:"cantik",happy:"gembira",sad:"sedih",strong:"kuat",peace:"aman",war:"perang",truth:"kebenaran",hope:"harapan",dream:"impian",country:"negara",language:"bahasa",health:"kesihatan",money:"wang",door:"pintu",road:"jalan",brother:"abang",sister:"kakak",father:"ayah",mother:"ibu"} },
  uk: { name:"Ukrainian", flag:"🇺🇦", tier:"premium", voice:"uk-UA", dict:{time:"час",year:"рік",day:"день",world:"світ",life:"життя",home:"дім",water:"вода",food:"їжа",family:"сім'я",friend:"друг",work:"робота",good:"добрий",new:"новий",old:"старий",love:"любов",city:"місто",name:"ім'я",book:"книга",school:"школа",morning:"ранок",night:"ніч",man:"чоловік",woman:"жінка",child:"дитина",hand:"рука",eye:"око",heart:"серце",sun:"сонце",moon:"місяць",tree:"дерево",dog:"собака",cat:"кіт",red:"червоний",blue:"синій",green:"зелений",yes:"так",no:"ні",hello:"привіт",thank:"дякую",sorry:"вибачте",beautiful:"красивий",happy:"щасливий",sad:"сумний",strong:"сильний",peace:"мир",war:"війна",truth:"правда",hope:"надія",dream:"мрія",country:"країна",language:"мова",health:"здоров'я",money:"гроші",door:"двері",road:"дорога",brother:"брат",sister:"сестра",father:"батько",mother:"мати"} },
  cs: { name:"Czech", flag:"🇨🇿", tier:"premium", voice:"cs-CZ", dict:{time:"čas",year:"rok",day:"den",world:"svět",life:"život",home:"domov",water:"voda",food:"jídlo",family:"rodina",friend:"přítel",work:"práce",good:"dobrý",new:"nový",old:"starý",love:"láska",city:"město",name:"jméno",book:"kniha",school:"škola",morning:"ráno",night:"noc",man:"muž",woman:"žena",child:"dítě",hand:"ruka",eye:"oko",heart:"srdce",sun:"slunce",moon:"měsíc",tree:"strom",dog:"pes",cat:"kočka",red:"červený",blue:"modrý",green:"zelený",yes:"ano",no:"ne",hello:"ahoj",thank:"díky",sorry:"promiňte",beautiful:"krásný",happy:"šťastný",sad:"smutný",strong:"silný",peace:"mír",war:"válka",truth:"pravda",hope:"naděje",dream:"sen",country:"země",language:"jazyk",health:"zdraví",money:"peníze",door:"dveře",road:"cesta",brother:"bratr",sister:"sestra",father:"otec",mother:"matka"} },
  hu: { name:"Hungarian", flag:"🇭🇺", tier:"premium", voice:"hu-HU", dict:{time:"idő",year:"év",day:"nap",world:"világ",life:"élet",home:"otthon",water:"víz",food:"étel",family:"család",friend:"barát",work:"munka",good:"jó",new:"új",old:"régi",love:"szerelem",city:"város",name:"név",book:"könyv",school:"iskola",morning:"reggel",night:"éjszaka",man:"férfi",woman:"nő",child:"gyerek",hand:"kéz",eye:"szem",heart:"szív",sun:"nap",moon:"hold",tree:"fa",dog:"kutya",cat:"macska",red:"piros",blue:"kék",green:"zöld",yes:"igen",no:"nem",hello:"szia",thank:"köszönöm",sorry:"bocsánat",beautiful:"szép",happy:"boldog",sad:"szomorú",strong:"erős",peace:"béke",war:"háború",truth:"igazság",hope:"remény",dream:"álom",country:"ország",language:"nyelv",health:"egészség",money:"pénz",door:"ajtó",road:"út",brother:"fivér",sister:"nővér",father:"apa",mother:"anya"} },
  ro: { name:"Romanian", flag:"🇷🇴", tier:"premium", voice:"ro-RO", dict:{time:"timp",year:"an",day:"zi",world:"lume",life:"viață",home:"acasă",water:"apă",food:"mâncare",family:"familie",friend:"prieten",work:"muncă",good:"bun",new:"nou",old:"vechi",love:"dragoste",city:"oraș",name:"nume",book:"carte",school:"școală",morning:"dimineață",night:"noapte",man:"bărbat",woman:"femeie",child:"copil",hand:"mână",eye:"ochi",heart:"inimă",sun:"soare",moon:"lună",tree:"copac",dog:"câine",cat:"pisică",red:"roșu",blue:"albastru",green:"verde",yes:"da",no:"nu",hello:"bună",thank:"mulțumesc",sorry:"scuze",beautiful:"frumos",happy:"fericit",sad:"trist",strong:"puternic",peace:"pace",war:"război",truth:"adevăr",hope:"speranță",dream:"vis",country:"țară",language:"limbă",health:"sănătate",money:"bani",door:"ușă",road:"drum",brother:"frate",sister:"soră",father:"tată",mother:"mamă"} },
  bn: { name:"Bengali", flag:"🇧🇩", tier:"premium", voice:"bn-IN", dict:{time:"সময়",year:"বছর",day:"দিন",world:"পৃথিবী",life:"জীবন",home:"বাড়ি",water:"পানি",food:"খাবার",family:"পরিবার",friend:"বন্ধু",work:"কাজ",good:"ভালো",new:"নতুন",old:"পুরানো",love:"ভালোবাসা",city:"শহর",name:"নাম",book:"বই",school:"স্কুল",morning:"সকাল",night:"রাত",man:"পুরুষ",woman:"মহিলা",child:"শিশু",hand:"হাত",eye:"চোখ",heart:"হৃদয়",sun:"সূর্য",moon:"চাঁদ",tree:"গাছ",dog:"কুকুর",cat:"বিড়াল",red:"লাল",blue:"নীল",green:"সবুজ",yes:"হ্যাঁ",no:"না",hello:"হ্যালো",thank:"ধন্যবাদ",sorry:"দুঃখিত",beautiful:"সুন্দর",happy:"খুশি",sad:"দুঃখী",strong:"শক্তিশালী",peace:"শান্তি",war:"যুদ্ধ",truth:"সত্য",hope:"আশা",dream:"স্বপ্ন",country:"দেশ",language:"ভাষা",health:"স্বাস্থ্য",money:"টাকা",door:"দরজা",road:"রাস্তা",brother:"ভাই",sister:"বোন",father:"বাবা",mother:"মা"} },
  te: { name:"Telugu", flag:"🇮🇳", tier:"premium", voice:"te-IN", dict:{time:"సమయం",year:"సంవత్సరం",day:"రోజు",world:"ప్రపంచం",life:"జీవితం",home:"ఇల్లు",water:"నీరు",food:"ఆహారం",family:"కుటుంబం",friend:"స్నేహితుడు",work:"పని",good:"మంచి",new:"కొత్త",old:"పాత",love:"ప్రేమ",city:"నగరం",name:"పేరు",book:"పుస్తకం",school:"పాఠశాల",morning:"ఉదయం",night:"రాత్రి",man:"మనిషి",woman:"స్త్రీ",child:"పిల్లవాడు",hand:"చేయి",eye:"కన్ను",heart:"హృదయం",sun:"సూర్యుడు",moon:"చంద్రుడు",tree:"చెట్టు",dog:"కుక్క",cat:"పిల్లి",red:"ఎరుపు",blue:"నీలం",green:"పచ్చ",yes:"అవును",no:"లేదు",hello:"నమస్కారం",thank:"ధన్యవాదాలు",sorry:"క్షమించండి",beautiful:"అందమైన",happy:"సంతోషం",sad:"విచారం",strong:"బలమైన",peace:"శాంతి",war:"యుద్ధం",truth:"సత్యం",hope:"ఆశ",dream:"కల",country:"దేశం",language:"భాష",health:"ఆరోగ్యం",money:"డబ్బు",door:"తలుపు",road:"రోడ్డు",brother:"అన్న",sister:"అక్క",father:"నాన్న",mother:"అమ్మ"} },
  mr: { name:"Marathi", flag:"🇮🇳", tier:"premium", voice:"mr-IN", dict:{time:"वेळ",year:"वर्ष",day:"दिवस",world:"जग",life:"जीवन",home:"घर",water:"पाणी",food:"अन्न",family:"कुटुंब",friend:"मित्र",work:"काम",good:"चांगले",new:"नवीन",old:"जुने",love:"प्रेम",city:"शहर",name:"नाव",book:"पुस्तक",school:"शाळा",morning:"सकाळ",night:"रात्र",man:"माणूस",woman:"स्त्री",child:"मूल",hand:"हात",eye:"डोळा",heart:"हृदय",sun:"सूर्य",moon:"चंद्र",tree:"झाड",dog:"कुत्रा",cat:"मांजर",red:"लाल",blue:"निळा",green:"हिरवा",yes:"हो",no:"नाही",hello:"नमस्कार",thank:"धन्यवाद",sorry:"माफ करा",beautiful:"सुंदर",happy:"आनंदी",sad:"दु:खी",strong:"मजबूत",peace:"शांती",war:"युद्ध",truth:"सत्य",hope:"आशा",dream:"स्वप्न",country:"देश",language:"भाषा",health:"आरोग्य",money:"पैसा",door:"दरवाजा",road:"रस्ता",brother:"भाऊ",sister:"बहीण",father:"वडील",mother:"आई"} },
  gu: { name:"Gujarati", flag:"🇮🇳", tier:"premium", voice:"gu-IN", dict:{time:"સમય",year:"વર્ષ",day:"દિવસ",world:"વિશ્વ",life:"જીવન",home:"ઘર",water:"પાણી",food:"ખોરાક",family:"કુટુંબ",friend:"મિત્ર",work:"કામ",good:"સારું",new:"નવું",old:"જૂનું",love:"પ્રેમ",city:"શહેર",name:"નામ",book:"પુસ્તક",school:"શાળા",morning:"સવાર",night:"રાત",man:"પુરુષ",woman:"સ્ત્રી",child:"બાળક",hand:"હાથ",eye:"આંખ",heart:"હૃદય",sun:"સૂર્ય",moon:"ચંદ્ર",tree:"વૃક્ષ",dog:"કૂતરો",cat:"બિલાડી",red:"લાલ",blue:"વાદળી",green:"લીલો",yes:"હા",no:"ના",hello:"નમસ્તે",thank:"આભાર",sorry:"માફ કરો",beautiful:"સુંદર",happy:"ખુશ",sad:"ઉદાસ",strong:"મજબૂત",peace:"શાંતિ",war:"યુદ્ધ",truth:"સત્ય",hope:"આશા",dream:"સ્વપ્ન",country:"દેશ",language:"ભાષા",health:"સ્વાસ્થ્ય",money:"પૈસા",door:"દરવાજો",road:"રસ્તો",brother:"ભાઈ",sister:"બહેન",father:"પિતા",mother:"માતા"} },
  kn: { name:"Kannada", flag:"🇮🇳", tier:"premium", voice:"kn-IN", dict:{time:"ಸಮಯ",year:"ವರ್ಷ",day:"ದಿನ",world:"ಜಗತ್ತು",life:"ಜೀವನ",home:"ಮನೆ",water:"ನೀರು",food:"ಆಹಾರ",family:"ಕುಟುಂಬ",friend:"ಗೆಳೆಯ",work:"ಕೆಲಸ",good:"ಒಳ್ಳೆಯ",new:"ಹೊಸ",old:"ಹಳೆಯ",love:"ಪ್ರೀತಿ",city:"ನಗರ",name:"ಹೆಸರು",book:"ಪುಸ್ತಕ",school:"ಶಾಲೆ",morning:"ಬೆಳಿಗ್ಗೆ",night:"ರಾತ್ರಿ",man:"ಮನುಷ್ಯ",woman:"ಮಹಿಳೆ",child:"ಮಗು",hand:"ಕೈ",eye:"ಕಣ್ಣು",heart:"ಹೃದಯ",sun:"ಸೂರ್ಯ",moon:"ಚಂದ್ರ",tree:"ಮರ",dog:"ನಾಯಿ",cat:"ಬೆಕ್ಕು",red:"ಕೆಂಪು",blue:"ನೀಲಿ",green:"ಹಸಿರು",yes:"ಹೌದು",no:"ಇಲ್ಲ",hello:"ನಮಸ್ಕಾರ",thank:"ಧನ್ಯವಾದ",sorry:"ಕ್ಷಮಿಸಿ",beautiful:"ಸುಂದರ",happy:"ಸಂತೋಷ",sad:"ದುಃಖ",strong:"ಬಲಶಾಲಿ",peace:"ಶಾಂತಿ",war:"ಯುದ್ಧ",truth:"ಸತ್ಯ",hope:"ಆಶೆ",dream:"ಕನಸು",country:"ದೇಶ",language:"ಭಾಷೆ",health:"ಆರೋಗ್ಯ",money:"ಹಣ",door:"ಬಾಗಿಲು",road:"ರಸ್ತೆ",brother:"ಅಣ್ಣ",sister:"ಅಕ್ಕ",father:"ತಂದೆ",mother:"ತಾಯಿ"} },
  pa: { name:"Punjabi", flag:"🇮🇳", tier:"premium", voice:"pa-IN", dict:{time:"ਸਮਾਂ",year:"ਸਾਲ",day:"ਦਿਨ",world:"ਦੁਨੀਆ",life:"ਜ਼ਿੰਦਗੀ",home:"ਘਰ",water:"ਪਾਣੀ",food:"ਖਾਣਾ",family:"ਪਰਿਵਾਰ",friend:"ਦੋਸਤ",work:"ਕੰਮ",good:"ਚੰਗਾ",new:"ਨਵਾਂ",old:"ਪੁਰਾਣਾ",love:"ਪਿਆਰ",city:"ਸ਼ਹਿਰ",name:"ਨਾਮ",book:"ਕਿਤਾਬ",school:"ਸਕੂਲ",morning:"ਸਵੇਰ",night:"ਰਾਤ",man:"ਮਰਦ",woman:"ਔਰਤ",child:"ਬੱਚਾ",hand:"ਹੱਥ",eye:"ਅੱਖ",heart:"ਦਿਲ",sun:"ਸੂਰਜ",moon:"ਚੰਦ",tree:"ਰੁੱਖ",dog:"ਕੁੱਤਾ",cat:"ਬਿੱਲੀ",red:"ਲਾਲ",blue:"ਨੀਲਾ",green:"ਹਰਾ",yes:"ਹਾਂ",no:"ਨਹੀਂ",hello:"ਸਤ ਸ੍ਰੀ ਅਕਾਲ",thank:"ਧੰਨਵਾਦ",sorry:"ਮਾਫ਼ ਕਰਨਾ",beautiful:"ਸੁੰਦਰ",happy:"ਖੁਸ਼",sad:"ਉਦਾਸ",strong:"ਮਜ਼ਬੂਤ",peace:"ਸ਼ਾਂਤੀ",war:"ਜੰਗ",truth:"ਸੱਚ",hope:"ਉਮੀਦ",dream:"ਸੁਪਨਾ",country:"ਦੇਸ਼",language:"ਭਾਸ਼ਾ",health:"ਸਿਹਤ",money:"ਪੈਸੇ",door:"ਦਰਵਾਜ਼ਾ",road:"ਸੜਕ",brother:"ਭਰਾ",sister:"ਭੈਣ",father:"ਪਿਤਾ",mother:"ਮਾਤਾ"} },
  ur: { name:"Urdu", flag:"🇵🇰", tier:"premium", voice:"ur-PK", dict:{time:"وقت",year:"سال",day:"دن",world:"دنیا",life:"زندگی",home:"گھر",water:"پانی",food:"کھانا",family:"خاندان",friend:"دوست",work:"کام",good:"اچھا",new:"نیا",old:"پرانا",love:"محبت",city:"شہر",name:"نام",book:"کتاب",school:"سکول",morning:"صبح",night:"رات",man:"مرد",woman:"عورت",child:"بچہ",hand:"ہاتھ",eye:"آنکھ",heart:"دل",sun:"سورج",moon:"چاند",tree:"درخت",dog:"کتا",cat:"بلی",red:"لال",blue:"نیلا",green:"سبز",yes:"ہاں",no:"نہیں",hello:"سلام",thank:"شکریہ",sorry:"معاف کریں",beautiful:"خوبصورت",happy:"خوش",sad:"اداس",strong:"مضبوط",peace:"امن",war:"جنگ",truth:"سچ",hope:"امید",dream:"خواب",country:"ملک",language:"زبان",health:"صحت",money:"پیسہ",door:"دروازہ",road:"سڑک",brother:"بھائی",sister:"بہن",father:"باپ",mother:"ماں"} },
  fa: { name:"Persian", flag:"🇮🇷", tier:"premium", voice:"fa-IR", dict:{time:"زمان",year:"سال",day:"روز",world:"جهان",life:"زندگی",home:"خانه",water:"آب",food:"غذا",family:"خانواده",friend:"دوست",work:"کار",good:"خوب",new:"جدید",old:"قدیمی",love:"عشق",city:"شهر",name:"نام",book:"کتاب",school:"مدرسه",morning:"صبح",night:"شب",man:"مرد",woman:"زن",child:"کودک",hand:"دست",eye:"چشم",heart:"قلب",sun:"خورشید",moon:"ماه",tree:"درخت",dog:"سگ",cat:"گربه",red:"قرمز",blue:"آبی",green:"سبز",yes:"بله",no:"نه",hello:"سلام",thank:"ممنون",sorry:"ببخشید",beautiful:"زیبا",happy:"خوشحال",sad:"غمگین",strong:"قوی",peace:"صلح",war:"جنگ",truth:"حقیقت",hope:"امید",dream:"رویا",country:"کشور",language:"زبان",health:"سلامتی",money:"پول",door:"در",road:"جاده",brother:"برادر",sister:"خواهر",father:"پدر",mother:"مادر"} },
  sw: { name:"Swahili", flag:"🇰🇪", tier:"premium", voice:"sw-KE", dict:{time:"wakati",year:"mwaka",day:"siku",world:"dunia",life:"maisha",home:"nyumbani",water:"maji",food:"chakula",family:"familia",friend:"rafiki",work:"kazi",good:"nzuri",new:"mpya",old:"ya zamani",love:"upendo",city:"jiji",name:"jina",book:"kitabu",school:"shule",morning:"asubuhi",night:"usiku",man:"mwanaume",woman:"mwanamke",child:"mtoto",hand:"mkono",eye:"jicho",heart:"moyo",sun:"jua",moon:"mwezi",tree:"mti",dog:"mbwa",cat:"paka",red:"nyekundu",blue:"bluu",green:"kijani",yes:"ndiyo",no:"hapana",hello:"jambo",thank:"asante",sorry:"samahani",beautiful:"mzuri",happy:"furaha",sad:"huzuni",strong:"nguvu",peace:"amani",war:"vita",truth:"ukweli",hope:"matumaini",dream:"ndoto",country:"nchi",language:"lugha",health:"afya",money:"pesa",door:"mlango",road:"barabara",brother:"kaka",sister:"dada",father:"baba",mother:"mama"} },
  af: { name:"Afrikaans", flag:"🇿🇦", tier:"premium", voice:"af-ZA", dict:{time:"tyd",year:"jaar",day:"dag",world:"wêreld",life:"lewe",home:"huis",water:"water",food:"kos",family:"familie",friend:"vriend",work:"werk",good:"goed",new:"nuut",old:"oud",love:"liefde",city:"stad",name:"naam",book:"boek",school:"skool",morning:"oggend",night:"nag",man:"man",woman:"vrou",child:"kind",hand:"hand",eye:"oog",heart:"hart",sun:"son",moon:"maan",tree:"boom",dog:"hond",cat:"kat",red:"rooi",blue:"blou",green:"groen",yes:"ja",no:"nee",hello:"hallo",thank:"dankie",sorry:"jammer",beautiful:"mooi",happy:"gelukkig",sad:"hartseer",strong:"sterk",peace:"vrede",war:"oorlog",truth:"waarheid",hope:"hoop",dream:"droom",country:"land",language:"taal",health:"gesondheid",money:"geld",door:"deur",road:"pad",brother:"broer",sister:"suster",father:"vader",mother:"moeder"} },
  sk: { name:"Slovak", flag:"🇸🇰", tier:"premium", voice:"sk-SK", dict:{time:"čas",year:"rok",day:"deň",world:"svet",life:"život",home:"domov",water:"voda",food:"jedlo",family:"rodina",friend:"priateľ",work:"práca",good:"dobrý",new:"nový",old:"starý",love:"láska",city:"mesto",name:"meno",book:"kniha",school:"škola",morning:"ráno",night:"noc",man:"muž",woman:"žena",child:"dieťa",hand:"ruka",eye:"oko",heart:"srdce",sun:"slnko",moon:"mesiac",tree:"strom",dog:"pes",cat:"mačka",red:"červený",blue:"modrý",green:"zelený",yes:"áno",no:"nie",hello:"ahoj",thank:"ďakujem",sorry:"prepáčte",beautiful:"krásny",happy:"šťastný",sad:"smutný",strong:"silný",peace:"mier",war:"vojna",truth:"pravda",hope:"nádej",dream:"sen",country:"krajina",language:"jazyk",health:"zdravie",money:"peniaze",door:"dvere",road:"cesta",brother:"brat",sister:"sestra",father:"otec",mother:"matka"} },
  hr: { name:"Croatian", flag:"🇭🇷", tier:"premium", voice:"hr-HR", dict:{time:"vrijeme",year:"godina",day:"dan",world:"svijet",life:"život",home:"dom",water:"voda",food:"hrana",family:"obitelj",friend:"prijatelj",work:"posao",good:"dobar",new:"nov",old:"star",love:"ljubav",city:"grad",name:"ime",book:"knjiga",school:"škola",morning:"jutro",night:"noć",man:"muškarac",woman:"žena",child:"dijete",hand:"ruka",eye:"oko",heart:"srce",sun:"sunce",moon:"mjesec",tree:"drvo",dog:"pas",cat:"mačka",red:"crven",blue:"plav",green:"zelen",yes:"da",no:"ne",hello:"bok",thank:"hvala",sorry:"oprostite",beautiful:"lijep",happy:"sretan",sad:"tužan",strong:"jak",peace:"mir",war:"rat",truth:"istina",hope:"nada",dream:"san",country:"zemlja",language:"jezik",health:"zdravlje",money:"novac",door:"vrata",road:"cesta",brother:"brat",sister:"sestra",father:"otac",mother:"majka"} },
  bg: { name:"Bulgarian", flag:"🇧🇬", tier:"premium", voice:"bg-BG", dict:{time:"време",year:"година",day:"ден",world:"свят",life:"живот",home:"дом",water:"вода",food:"храна",family:"семейство",friend:"приятел",work:"работа",good:"добър",new:"нов",old:"стар",love:"любов",city:"град",name:"име",book:"книга",school:"училище",morning:"утро",night:"нощ",man:"мъж",woman:"жена",child:"дете",hand:"ръка",eye:"очи",heart:"сърце",sun:"слънце",moon:"луна",tree:"дърво",dog:"куче",cat:"котка",red:"червен",blue:"син",green:"зелен",yes:"да",no:"не",hello:"здравей",thank:"благодаря",sorry:"съжалявам",beautiful:"красив",happy:"щастлив",sad:"тъжен",strong:"силен",peace:"мир",war:"война",truth:"истина",hope:"надежда",dream:"сън",country:"страна",language:"език",health:"здраве",money:"пари",door:"врата",road:"път",brother:"брат",sister:"сестра",father:"баща",mother:"майка"} },
  sr: { name:"Serbian", flag:"🇷🇸", tier:"premium", voice:"sr-RS", dict:{time:"време",year:"година",day:"дан",world:"свет",life:"живот",home:"дом",water:"вода",food:"храна",family:"породица",friend:"пријатељ",work:"посао",good:"добар",new:"нов",old:"стар",love:"љубав",city:"град",name:"име",book:"књига",school:"школа",morning:"јутро",night:"ноћ",man:"мушкарац",woman:"жена",child:"дете",hand:"рука",eye:"око",heart:"срце",sun:"сунце",moon:"месец",tree:"дрво",dog:"пас",cat:"мачка",red:"црвен",blue:"плав",green:"зелен",yes:"да",no:"не",hello:"здраво",thank:"хвала",sorry:"извините",beautiful:"леп",happy:"срећан",sad:"тужан",strong:"јак",peace:"мир",war:"рат",truth:"истина",hope:"нада",dream:"сан",country:"земља",language:"језик",health:"здравље",money:"новац",door:"врата",road:"пут",brother:"брат",sister:"сестра",father:"отац",mother:"мајка"} },
  lt: { name:"Lithuanian", flag:"🇱🇹", tier:"premium", voice:"lt-LT", dict:{time:"laikas",year:"metai",day:"diena",world:"pasaulis",life:"gyvenimas",home:"namai",water:"vanduo",food:"maistas",family:"šeima",friend:"draugas",work:"darbas",good:"geras",new:"naujas",old:"senas",love:"meilė",city:"miestas",name:"vardas",book:"knyga",school:"mokykla",morning:"rytas",night:"naktis",man:"vyras",woman:"moteris",child:"vaikas",hand:"ranka",eye:"akis",heart:"širdis",sun:"saulė",moon:"mėnulis",tree:"medis",dog:"šuo",cat:"katė",red:"raudona",blue:"mėlyna",green:"žalia",yes:"taip",no:"ne",hello:"labas",thank:"ačiū",sorry:"atsiprašau",beautiful:"gražus",happy:"laimingas",sad:"liūdnas",strong:"stiprus",peace:"taika",war:"karas",truth:"tiesa",hope:"viltis",dream:"svajonė",country:"šalis",language:"kalba",health:"sveikata",money:"pinigai",door:"durys",road:"kelias",brother:"brolis",sister:"sesuo",father:"tėvas",mother:"mama"} },
  lv: { name:"Latvian", flag:"🇱🇻", tier:"premium", voice:"lv-LV", dict:{time:"laiks",year:"gads",day:"diena",world:"pasaule",life:"dzīve",home:"mājas",water:"ūdens",food:"ēdiens",family:"ģimene",friend:"draugs",work:"darbs",good:"labs",new:"jauns",old:"vecs",love:"mīlestība",city:"pilsēta",name:"vārds",book:"grāmata",school:"skola",morning:"rīts",night:"nakts",man:"vīrietis",woman:"sieviete",child:"bērns",hand:"roka",eye:"acs",heart:"sirds",sun:"saule",moon:"mēness",tree:"koks",dog:"suns",cat:"kaķis",red:"sarkans",blue:"zils",green:"zaļš",yes:"jā",no:"nē",hello:"sveiki",thank:"paldies",sorry:"atvainojiet",beautiful:"skaists",happy:"laimīgs",sad:"skumjš",strong:"stiprs",peace:"miers",war:"karš",truth:"patiesība",hope:"cerība",dream:"sapnis",country:"valsts",language:"valoda",health:"veselība",money:"nauda",door:"durvis",road:"ceļš",brother:"brālis",sister:"māsa",father:"tēvs",mother:"māte"} },
  et: { name:"Estonian", flag:"🇪🇪", tier:"premium", voice:"et-EE", dict:{time:"aeg",year:"aasta",day:"päev",world:"maailm",life:"elu",home:"kodu",water:"vesi",food:"toit",family:"perekond",friend:"sõber",work:"töö",good:"hea",new:"uus",old:"vana",love:"armastus",city:"linn",name:"nimi",book:"raamat",school:"kool",morning:"hommik",night:"öö",man:"mees",woman:"naine",child:"laps",hand:"käsi",eye:"silm",heart:"süda",sun:"päike",moon:"kuu",tree:"puu",dog:"koer",cat:"kass",red:"punane",blue:"sinine",green:"roheline",yes:"jah",no:"ei",hello:"tere",thank:"tänan",sorry:"vabandage",beautiful:"ilus",happy:"õnnelik",sad:"kurb",strong:"tugev",peace:"rahu",war:"sõda",truth:"tõde",hope:"lootus",dream:"unistus",country:"riik",language:"keel",health:"tervis",money:"raha",door:"uks",road:"tee",brother:"vend",sister:"õde",father:"isa",mother:"ema"} },
  ca: { name:"Catalan", flag:"🇪🇸", tier:"premium", voice:"ca-ES", dict:{time:"temps",year:"any",day:"dia",world:"món",life:"vida",home:"casa",water:"aigua",food:"menjar",family:"família",friend:"amic",work:"treball",good:"bo",new:"nou",old:"vell",love:"amor",city:"ciutat",name:"nom",book:"llibre",school:"escola",morning:"matí",night:"nit",man:"home",woman:"dona",child:"nen",hand:"mà",eye:"ull",heart:"cor",sun:"sol",moon:"lluna",tree:"arbre",dog:"gos",cat:"gat",red:"vermell",blue:"blau",green:"verd",yes:"sí",no:"no",hello:"hola",thank:"gràcies",sorry:"perdó",beautiful:"bonic",happy:"feliç",sad:"trist",strong:"fort",peace:"pau",war:"guerra",truth:"veritat",hope:"esperança",dream:"somni",country:"país",language:"idioma",health:"salut",money:"diners",door:"porta",road:"camí",brother:"germà",sister:"germana",father:"pare",mother:"mare"} }
};
